// Phase 5.5 — Break-glass secret.
//
// A one-shot high-entropy secret generated by the Self-Hosted install
// during setup. Displayed exactly once; only a scrypt hash is persisted in
// `platform_config.break_glass_hash`. Presenting the plaintext later flips
// the install into recovery mode without contacting the MC.
//
// This is LOCAL to the self-hosted install. The MC never sees it.

import { randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

const SECRET_BYTES = 24; // 24 bytes → 39-char base32
const SCRYPT_N = 1 << 15;
const SCRYPT_R = 8;
const SCRYPT_P = 1;
const KEY_LEN = 32;
// 128 * N * r ≈ 32 MB; give scryptSync headroom above the 32 MB Node default.
const SCRYPT_MAXMEM = 64 * 1024 * 1024;

/** Human-friendly base32 (Crockford, no I/L/O/U) for readability. */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
function toBase32(buf: Buffer): string {
  let out = "";
  let bits = 0;
  let value = 0;
  for (const byte of buf) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      bits -= 5;
      out += ALPHABET[(value >>> bits) & 0x1f];
    }
  }
  if (bits > 0) out += ALPHABET[(value << (5 - bits)) & 0x1f];
  return out.replace(/(.{5})(?=.)/g, "$1-");
}

/** Generate a fresh plaintext secret + its salted scrypt hash string. */
export function generateBreakGlassSecret(): { plaintext: string; hash: string } {
  const raw = randomBytes(SECRET_BYTES);
  const plaintext = toBase32(raw);
  const salt = randomBytes(16);
  const derived = scryptSync(plaintext, salt, KEY_LEN, {
    N: SCRYPT_N,
    r: SCRYPT_R,
    p: SCRYPT_P,
    maxmem: SCRYPT_MAXMEM,
  });
  const hash = `scrypt$${SCRYPT_N}$${SCRYPT_R}$${SCRYPT_P}$${salt.toString("base64")}$${derived.toString("base64")}`;
  return { plaintext, hash };
}

/** Constant-time verify of a candidate plaintext against a stored hash. */
export function verifyBreakGlassSecret(
  candidate: string,
  hash: string | null | undefined,
): boolean {
  if (!hash || typeof hash !== "string") return false;
  const parts = hash.split("$");
  if (parts.length !== 6 || parts[0] !== "scrypt") return false;
  const [, nStr, rStr, pStr, saltB64, derivedB64] = parts;
  const N = Number(nStr),
    r = Number(rStr),
    p = Number(pStr);
  if (!Number.isFinite(N) || !Number.isFinite(r) || !Number.isFinite(p)) return false;
  const salt = Buffer.from(saltB64, "base64");
  const expected = Buffer.from(derivedB64, "base64");
  let candidateDerived: Buffer;
  try {
    candidateDerived = scryptSync(candidate.trim().toUpperCase(), salt, expected.length, {
      N,
      r,
      p,
      maxmem: SCRYPT_MAXMEM,
    });
  } catch {
    return false;
  }
  if (candidateDerived.length !== expected.length) return false;
  return timingSafeEqual(candidateDerived, expected);
}
