// Base64-encoded installer binaries embedded in the app bundle.
//
// Regenerated by scripts/build-installer.sh (which runs `go build` for each
// target and then re-encodes the resulting binaries as base64 constants into
// this file). Checked in so the server bundle stays self-contained in the
// Cloudflare Worker runtime, which has no filesystem access to installer/dist.
//
// The values below are 1-byte placeholders ("#") so tests and dev builds pass
// without a Go toolchain. The release pipeline overwrites this file with the
// real binaries before publishing the app.

export const INSTALL_EXE_B64 = "Iw==";
export const INSTALL_MACOS_B64 = "Iw==";
export const INSTALL_LINUX_B64 = "Iw==";
