// Subscription engine — single source of truth for what a plan unlocks.
// Selecting a plan automatically derives every other value used by the
// Customer Workspace Manager and by document generation.

export type SubscriptionPlanKey = "pilot" | "standard" | "business" | "enterprise";

export interface SubscriptionPlan {
  key: SubscriptionPlanKey;
  label: string;
  maxUsers: number | null; // null = unlimited
  storageGB: number;
  academy: boolean;
  aiFeatures: "basic" | "standard" | "advanced" | "full";
  analytics: "basic" | "standard" | "advanced" | "full";
  support: string;
  workspaceLimit: number | null;
  /** Feature keys (from `feature-catalog.ts`) that are enabled by default. */
  modules: string[];
  /** Templates auto-generated by "Generate All Standard Documents". */
  recommendedTemplates: string[];
}

const ALL_MODULES = [
  "ai_assistant",
  "source_citations",
  "ai_sop_generator",
  "ai_workspace_audit",
  "ai_workspace",
  "knowledge_base",
  "faq",
  "knowledge_gaps",
  "internal_requests",
  "sop_versioning",
  "confidence_scoring",
  "audit_log",
  "rbac",
  "workspace_isolation",
  "compliance_center",
  "platform_admin",
  "executive_dashboard",
  "analytics",
  "reports",
  "enterprise_export",
  "support_center",
  "workspace_health",
  "brand_center",
  "academy",
  "multi_language",
  "bilingual_ui",
  "pwa",
  "notifications",
];

export const SUBSCRIPTION_PLANS: Record<SubscriptionPlanKey, SubscriptionPlan> = {
  pilot: {
    key: "pilot",
    label: "Pilot",
    maxUsers: 25,
    storageGB: 5,
    academy: false,
    aiFeatures: "basic",
    analytics: "basic",
    support: "Email support, business hours",
    workspaceLimit: 1,
    modules: [
      "ai_assistant",
      "source_citations",
      "knowledge_base",
      "faq",
      "knowledge_gaps",
      "internal_requests",
      "bilingual_ui",
      "pwa",
      "notifications",
    ],
    recommendedTemplates: [
      "pilot_proposal",
      "executive_summary",
      "implementation_plan",
      "onboarding_guide",
    ],
  },
  standard: {
    key: "standard",
    label: "Standard",
    maxUsers: 100,
    storageGB: 25,
    academy: true,
    aiFeatures: "standard",
    analytics: "standard",
    support: "Business hours, 8x5",
    workspaceLimit: 1,
    modules: [
      "ai_assistant",
      "source_citations",
      "ai_sop_generator",
      "knowledge_base",
      "faq",
      "knowledge_gaps",
      "internal_requests",
      "sop_versioning",
      "confidence_scoring",
      "audit_log",
      "rbac",
      "workspace_isolation",
      "analytics",
      "reports",
      "executive_dashboard",
      "support_center",
      "workspace_health",
      "academy",
      "multi_language",
      "bilingual_ui",
      "pwa",
      "notifications",
    ],
    recommendedTemplates: [
      "executive_summary",
      "commercial_proposal",
      "implementation_plan",
      "training_plan",
      "support_plan",
      "onboarding_guide",
    ],
  },
  business: {
    key: "business",
    label: "Business",
    maxUsers: 500,
    storageGB: 100,
    academy: true,
    aiFeatures: "advanced",
    analytics: "advanced",
    support: "Priority support, 24x5",
    workspaceLimit: 3,
    modules: [
      ...ALL_MODULES.filter(
        (m) => m !== "brand_center" && m !== "compliance_center" && m !== "platform_admin",
      ),
    ],
    recommendedTemplates: [
      "executive_summary",
      "commercial_proposal",
      "technical_proposal",
      "architecture_overview",
      "feature_matrix",
      "security_overview",
      "implementation_plan",
      "training_plan",
      "support_plan",
      "onboarding_guide",
      "service_agreement",
      "data_processing_agreement",
    ],
  },
  enterprise: {
    key: "enterprise",
    label: "Enterprise",
    maxUsers: null,
    storageGB: 500,
    academy: true,
    aiFeatures: "full",
    analytics: "full",
    support: "24x7 + dedicated Customer Success Manager",
    workspaceLimit: null,
    modules: ALL_MODULES,
    recommendedTemplates: [
      "enterprise_overview",
      "executive_summary",
      "commercial_proposal",
      "technical_proposal",
      "architecture_overview",
      "deployment_guide",
      "feature_matrix",
      "security_overview",
      "compliance_overview",
      "gdpr_overview",
      "service_agreement",
      "data_processing_agreement",
      "sla",
      "implementation_plan",
      "training_plan",
      "support_plan",
      "onboarding_guide",
      "customer_success_plan",
      "renewal_summary",
    ],
  },
};

export function resolvePlan(key: string | null | undefined): SubscriptionPlan {
  const k = (key ?? "").toLowerCase() as SubscriptionPlanKey;
  return SUBSCRIPTION_PLANS[k] ?? SUBSCRIPTION_PLANS.standard;
}

export const SUBSCRIPTION_PLAN_LIST = Object.values(SUBSCRIPTION_PLANS);
