import { createFileRoute } from "@tanstack/react-router";
import { DraftDisclaimer } from "@/components/legal/draft-disclaimer";

export const Route = createFileRoute("/legal/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — OPSQAI" },
      {
        name: "description",
        content:
          "Terms governing the use of opsqai.de and the OPSQAI application. Draft — pending final legal review.",
      },
      { property: "og:url", content: "https://opsqai.de/legal/terms" },
      {
        property: "og:description",
        content:
          "Terms governing the use of opsqai.de and the OPSQAI application. Draft — pending final legal review.",
      },
    ],
    links: [{ rel: "canonical", href: "https://opsqai.de/legal/terms" }],
  }),
  component: () => (
    <>
      <h1>Terms of Service</h1>
      <DraftDisclaimer />
      <p>
        These Terms govern your use of the OPSQAI marketing site (opsqai.de) and the OPSQAI
        application. By using OPSQAI you agree to these Terms.
      </p>

      <h2>Accounts</h2>
      <p>
        OPSQAI is provided to companies under a written agreement. End-user accounts are provisioned
        by your company administrator and are personal to the assigned user.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not upload content you do not have the right to share.</li>
        <li>
          Do not attempt to exfiltrate other tenants' data, bypass access controls, or reverse
          engineer the platform.
        </li>
        <li>Do not use OPSQAI to generate unlawful or harmful content.</li>
      </ul>

      <h2>AI output</h2>
      <p>
        OPSQAI answers are generated by AI models from your company's source documents. While the
        platform is designed to ground answers strictly in cited sources, outputs may still contain
        errors. Customers must review answers before acting on them in safety-critical contexts.
      </p>

      <h2>Service availability</h2>
      <p>
        We aim for high availability and maintain backups, but the service is provided on an "as is"
        and "as available" basis, except where a written enterprise agreement specifies otherwise.
      </p>

      <h2>Termination</h2>
      <p>
        Either party may terminate per the underlying agreement. On termination, customer data is
        exported and deleted per the Privacy Policy and the Data Processing Agreement.
      </p>

      <h2>Governing law</h2>
      <p>
        These Terms are governed by the law specified in the customer's written agreement. Where
        none is specified, German law applies.
      </p>
    </>
  ),
});
