// Bootstrap script run once by NSIS after files are staged.
//   node bootstrap/init.js --company "Acme" --admin-email "a@b.com" --admin-password "..." --install-id <uuid>
//
// Phase 2 responsibilities:
//   1. Write %ProgramData%\OPSQAI\config\config.json atomically (owner-only ACL).
//   2. Start OpsqaiDatabase, wait for TCP readiness on 127.0.0.1:<port>.
//      (OpsqaiDatabase generates its own scram-sha-256 password on first init.)
//   3. Run app migrations from %ProgramFiles%\OPSQAI\app\server\migrate.mjs.
//   4. Trust Caddy's local root CA into LocalMachine\Root.
//   5. Start OpsqaiCaddy + OpsqaiPlatform, then health-probe https://localhost/health.
//
// Wizard integration lands in Phase 3 — this script is the contract the
// wizard invokes at step 9 (Install).

'use strict';
const fs = require('fs');
const path = require('path');
const net = require('net');
const https = require('https');
const crypto = require('crypto');
const { execFileSync, spawnSync } = require('child_process');
const { programData, programFiles, saveConfig } = require('../common/config');

function arg(name, dflt) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : dflt;
}
function log(m) { console.log(`[bootstrap] ${m}`); }

const installId     = arg('install-id', crypto.randomUUID());
const companyName   = arg('company', 'OPSQAI Customer');
const adminEmail    = arg('admin-email');
const adminPassword = arg('admin-password');
const dbMode        = arg('db-mode', 'embedded');
const storageMode   = arg('storage-mode', 'local');
const startServices = arg('start-services', 'true') !== 'false';

if (!adminEmail || !adminPassword) {
  console.error('Usage: init.js --admin-email <e> --admin-password <p> [--company <name>]');
  process.exit(2);
}

const config = {
  version: '1.0.0',
  installId,
  company: { name: companyName, contactEmail: adminEmail, timezone: 'UTC' },
  database: dbMode === 'embedded'
    ? { mode: 'embedded', embedded: { port: 55432 } } // password generated by OpsqaiDatabase
    : { mode: 'external', external: JSON.parse(arg('db-external', '{}')) },
  storage: storageMode === 'local'
    ? { mode: 'local', local: { path: programData('data', 'storage') } }
    : { mode: 's3', s3: JSON.parse(arg('storage-s3', '{}')) },
  ai: JSON.parse(arg('ai', '{"provider":"none"}')),
  updates: { channel: 'stable', manifestUrl: 'https://updates.opsqai.de/channel/stable/manifest.json' },
};

fs.mkdirSync(programData('config'), { recursive: true });
fs.mkdirSync(programData('data', 'storage'), { recursive: true });
fs.mkdirSync(programData('logs'), { recursive: true });
saveConfig(config);
log(`wrote config`);

// Lock config file ACL — Administrators + SYSTEM only.
try {
  const cfgFile = path.join(programData('config'), 'config.json');
  execFileSync('icacls.exe', [cfgFile, '/inheritance:r',
    '/grant:r', 'SYSTEM:F', '/grant:r', 'BUILTIN\\Administrators:F'], { stdio: 'inherit' });
} catch (e) {
  console.warn(`[bootstrap] icacls on config failed: ${e.message}`);
}

function svcCmd(name, action) {
  const svc = programFiles('winsw', `${name}.exe`);
  if (!fs.existsSync(svc)) { log(`skip ${action} ${name} (winsw wrapper not found)`); return 0; }
  const r = spawnSync(svc, [action], { stdio: 'inherit' });
  return r.status ?? 0;
}
function waitTcp(host, port, ms = 60_000) {
  const start = Date.now();
  return new Promise((resolve) => {
    (function attempt() {
      const s = net.connect(port, host);
      s.once('connect', () => { s.end(); resolve(true); });
      s.once('error', () => {
        if (Date.now() - start > ms) return resolve(false);
        setTimeout(attempt, 1000);
      });
    })();
  });
}
function httpsGet(url, ms = 30_000) {
  return new Promise((resolve) => {
    const req = https.get(url, { rejectUnauthorized: false, timeout: ms }, (res) => {
      let body = ''; res.on('data', (c) => body += c);
      res.on('end', () => resolve({ status: res.statusCode, body }));
    });
    req.on('error', (e) => resolve({ status: 0, error: e.message }));
    req.on('timeout', () => { req.destroy(); resolve({ status: 0, error: 'timeout' }); });
  });
}

(async function main() {
  // --- 1. Start database ---
  if (dbMode === 'embedded' && startServices) {
    log('starting OpsqaiDatabase');
    svcCmd('OpsqaiDatabase', 'start');
    const port = config.database.embedded.port;
    const ok = await waitTcp('127.0.0.1', port, 60_000);
    if (!ok) { console.error('[bootstrap] postgres not ready after 60s'); process.exit(3); }
    log(`postgres ready on 127.0.0.1:${port}`);
  }

  // --- 2. Run app migrations ---
  const migrator = programFiles('app', 'server', 'migrate.mjs');
  if (fs.existsSync(migrator)) {
    log('running app migrations');
    try {
      execFileSync(programFiles('runtime', 'node', 'node.exe'), [migrator], {
        stdio: 'inherit',
        env: {
          ...process.env,
          OPSQAI_ADMIN_EMAIL: adminEmail,
          OPSQAI_ADMIN_PASSWORD: adminPassword,
          OPSQAI_CONFIG: path.join(programData('config'), 'config.json'),
        },
      });
    } catch (e) {
      console.error(`[bootstrap] migrations failed: ${e.message}`);
      process.exit(4);
    }
  } else {
    log(`app migrator not present at ${migrator} — skipping (Phase 2 skeleton)`);
  }

  // --- 3. Start Caddy so it emits the local CA, then trust it ---
  if (startServices) {
    log('starting OpsqaiCaddy');
    svcCmd('OpsqaiCaddy', 'start');
    // Caddy writes root.crt within a few seconds of first start.
    const rootCert = programData('certs', 'pki', 'authorities', 'local', 'root.crt');
    for (let i = 0; i < 30 && !fs.existsSync(rootCert); i++) {
      await new Promise((r) => setTimeout(r, 1000));
    }
    if (fs.existsSync(rootCert)) {
      try {
        execFileSync('certutil.exe', ['-addstore', '-f', 'Root', rootCert], { stdio: 'inherit' });
        log('Caddy root CA trusted in LocalMachine\\Root');
      } catch (e) {
        console.warn(`[bootstrap] failed to trust Caddy root: ${e.message}`);
      }
    } else {
      console.warn('[bootstrap] Caddy root CA not produced within 30s — browsers may show a warning');
    }
  }

  // --- 4. Start platform + worker + updater ---
  if (startServices) {
    log('starting OpsqaiPlatform');
    svcCmd('OpsqaiPlatform', 'start');
    svcCmd('OpsqaiWorker',   'start');
    svcCmd('OpsqaiUpdater',  'start');

    // --- 5. Health probe ---
    log('probing https://localhost/health');
    let ok = false;
    for (let i = 0; i < 30; i++) {
      const r = await httpsGet('https://localhost/health', 5000);
      if (r.status && r.status >= 200 && r.status < 500) {
        log(`health OK (HTTP ${r.status}) after ${i + 1}s`);
        ok = true; break;
      }
      await new Promise((r) => setTimeout(r, 1000));
    }
    if (!ok) {
      console.error('[bootstrap] health probe failed — check %ProgramData%\\OPSQAI\\logs');
      process.exit(5);
    }
  }

  log('done');
})().catch((e) => { console.error(`[bootstrap] fatal: ${e.stack || e.message}`); process.exit(99); });
