// Bootstrap script run once by NSIS after files are staged.
//   node bootstrap/init.js --company "Acme" --admin-email "a@b.com" --admin-password "..." --install-id <uuid>
//
// Phase 2 responsibilities:
//   1. Write %ProgramData%\OPSQAI\config\config.json atomically (owner-only ACL).
//   2. Start OpsqaiDatabase, wait for TCP readiness on 127.0.0.1:<port>.
//      (OpsqaiDatabase generates its own scram-sha-256 password on first init.)
//   3. Run app migrations from %ProgramFiles%\OPSQAI\app\server\migrate.mjs.
//   4. Trust Caddy's local root CA into LocalMachine\Root.
//   5. Start OpsqaiCaddy + OpsqaiPlatform, then health-probe https://localhost/health.
//
// Phase 2.1: readiness now uses pg_isready + TCP, waits up to 120s, and on
// failure tails the postgres server log and the winsw wrapper logs so the
// operator has something to act on.

"use strict";
const fs = require("fs");
const path = require("path");
const net = require("net");
const https = require("https");
const crypto = require("crypto");
const { execFileSync, spawnSync } = require("child_process");
const { programData, programFiles, saveConfig } = require("../common/config");

function arg(name, dflt) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : dflt;
}
function log(m) {
  console.log(`[bootstrap] ${m}`);
}

const installId = arg("install-id", crypto.randomUUID());
const companyName = arg("company", "OPSQAI Customer");
const adminEmail = arg("admin-email");
const adminPassword = arg("admin-password");
const dbMode = arg("db-mode", "embedded");
const storageMode = arg("storage-mode", "local");
const licenseContents = arg("license", "");
const smtpJson = arg("smtp", "");
const startServices = arg("start-services", "true") !== "false";

if (!adminEmail || !adminPassword) {
  console.error("Usage: init.js --admin-email <e> --admin-password <p> [--company <name>]");
  process.exit(2);
}

// Parse license claims (structural only — real verification runs in the
// platform via local-licensing.server.ts once services start).
let licenseClaims = null;
if (licenseContents) {
  try {
    const parts = licenseContents.split(".");
    if (parts.length === 3) {
      licenseClaims = JSON.parse(
        Buffer.from(parts[1].replace(/-/g, "+").replace(/_/g, "/"), "base64").toString("utf8"),
      );
    }
  } catch (e) {
    console.warn(`[bootstrap] cannot parse license claims: ${e.message}`);
  }
}

const smtpCfg = smtpJson ? JSON.parse(smtpJson) : null;

const config = {
  version: "1.0.0",
  installId,
  company: { name: companyName, contactEmail: adminEmail, timezone: "UTC" },
  database:
    dbMode === "embedded"
      ? { mode: "embedded", embedded: { port: 55432 } } // password generated by OpsqaiDatabase
      : { mode: "external", external: JSON.parse(arg("db-external", "{}")) },
  storage:
    storageMode === "local"
      ? { mode: "local", local: { path: programData("data", "storage") } }
      : { mode: "s3", s3: JSON.parse(arg("storage-s3", "{}")) },
  ai: JSON.parse(arg("ai", '{"provider":"none"}')),
  smtp: smtpCfg,
  license: licenseClaims
    ? {
        edition: licenseClaims.edition ?? licenseClaims.tier ?? "community",
        seats: licenseClaims.seats ?? null,
        customer: licenseClaims.customer ?? licenseClaims.sub ?? null,
        exp: licenseClaims.exp ?? null,
        modules: Array.isArray(licenseClaims.modules) ? licenseClaims.modules : [],
      }
    : { edition: "community" },
  updates: {
    channel: "stable",
    manifestUrl: "https://updates.opsqai.de/channel/stable/manifest.json",
  },
};

fs.mkdirSync(programData("config"), { recursive: true });
fs.mkdirSync(programData("config", "keys"), { recursive: true });
fs.mkdirSync(programData("data", "storage"), { recursive: true });
fs.mkdirSync(programData("logs"), { recursive: true });
saveConfig(config);
log(`wrote config`);

// --- Write license file (if provided) --------------------------------------
if (licenseContents) {
  const licPath = path.join(programData("config"), "license.opsqai");
  try {
    fs.writeFileSync(licPath, licenseContents, { encoding: "utf8", mode: 0o600 });
    log(`wrote license file (${licenseContents.length} bytes)`);
    try {
      execFileSync(
        "icacls.exe",
        [licPath, "/inheritance:r", "/grant:r", "SYSTEM:F", "/grant:r", "BUILTIN\\Administrators:F"],
        { stdio: "ignore" },
      );
    } catch {}
  } catch (e) {
    console.warn(`[bootstrap] cannot write license: ${e.message}`);
  }
}

// --- Generate JWT signing keypair (Ed25519) if not present -----------------
const jwtPriv = path.join(programData("config", "keys"), "jwt-signing.key");
const jwtPub = path.join(programData("config", "keys"), "jwt-signing.pub");
if (!fs.existsSync(jwtPriv) || !fs.existsSync(jwtPub)) {
  const { generateKeyPairSync } = require("crypto");
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  fs.writeFileSync(jwtPriv, privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 });
  fs.writeFileSync(jwtPub, publicKey.export({ type: "spki", format: "pem" }));
  log("generated Ed25519 JWT signing keypair");
  try {
    execFileSync(
      "icacls.exe",
      [jwtPriv, "/inheritance:r", "/grant:r", "SYSTEM:F", "/grant:r", "BUILTIN\\Administrators:F"],
      { stdio: "ignore" },
    );
  } catch {}
}

// --- Stage bundled license verification public key -------------------------
// The updater ships pubkey.pem inside the payload; we copy it into
// config\keys so local-licensing.server.ts can find it via env.
const bundledLicensePub = programFiles("payload", "updater", "pubkey.pem");
const configLicensePub = path.join(programData("config", "keys"), "license-verify.pub");
if (fs.existsSync(bundledLicensePub) && !fs.existsSync(configLicensePub)) {
  try {
    fs.copyFileSync(bundledLicensePub, configLicensePub);
    log("staged license verification public key");
  } catch (e) {
    console.warn(`[bootstrap] cannot stage license verify key: ${e.message}`);
  }
}

// Lock config file ACL — Administrators + SYSTEM only.
try {
  const cfgFile = path.join(programData("config"), "config.json");
  execFileSync(
    "icacls.exe",
    [cfgFile, "/inheritance:r", "/grant:r", "SYSTEM:F", "/grant:r", "BUILTIN\\Administrators:F"],
    { stdio: "inherit" },
  );
} catch (e) {
  console.warn(`[bootstrap] icacls on config failed: ${e.message}`);
}

function svcCmd(name, action) {
  const svc = programFiles("winsw", `${name}.exe`);
  if (!fs.existsSync(svc)) {
    log(`skip ${action} ${name} (winsw wrapper not found)`);
    return 0;
  }
  const r = spawnSync(svc, [action], { stdio: "inherit" });
  return r.status ?? 0;
}
function waitTcp(host, port, ms) {
  const start = Date.now();
  return new Promise((resolve) => {
    (function attempt() {
      const s = net.connect(port, host);
      s.once("connect", () => {
        s.end();
        resolve(true);
      });
      s.once("error", () => {
        if (Date.now() - start > ms) return resolve(false);
        setTimeout(attempt, 1000);
      });
    })();
  });
}
function pgIsReady(port, timeoutMs) {
  const bin = programFiles("pgsql", "bin", "pg_isready.exe");
  if (!fs.existsSync(bin)) return { available: false };
  const deadline = Date.now() + timeoutMs;
  let last = { status: -1, out: "", err: "" };
  while (Date.now() < deadline) {
    const r = spawnSync(
      bin,
      ["-h", "127.0.0.1", "-p", String(port), "-U", "opsqai", "-d", "postgres", "-t", "3"],
      { encoding: "utf8" },
    );
    last = { status: r.status ?? -1, out: (r.stdout || "").trim(), err: (r.stderr || "").trim() };
    if (last.status === 0) return { available: true, ready: true, ...last };
    const wait = spawnSync("cmd", ["/c", "ping", "127.0.0.1", "-n", "2", ">nul"]);
    void wait;
  }
  return { available: true, ready: false, ...last };
}
function tailFile(p, lines = 80) {
  try {
    if (!fs.existsSync(p)) return null;
    const txt = fs.readFileSync(p, "utf8").split(/\r?\n/);
    return txt.slice(-lines).join("\n");
  } catch (e) {
    return `(cannot read ${p}: ${e.message})`;
  }
}
function newestFile(dir, pattern) {
  try {
    if (!fs.existsSync(dir)) return null;
    const files = fs
      .readdirSync(dir)
      .filter((f) => pattern.test(f))
      .map((f) => ({ f, m: fs.statSync(path.join(dir, f)).mtimeMs }))
      .sort((a, b) => b.m - a.m);
    return files.length ? path.join(dir, files[0].f) : null;
  } catch {
    return null;
  }
}
function dumpDbDiagnostics() {
  console.error("[bootstrap] --- database diagnostics ---");
  const pgLog = newestFile(programData("data", "pgsql", "log"), /\.log$/i);
  if (pgLog) {
    console.error(`[bootstrap] postgres log: ${pgLog}`);
    console.error(tailFile(pgLog) ?? "(empty)");
  } else {
    console.error(`[bootstrap] no postgres log file found in ${programData("data", "pgsql", "log")}`);
  }
  for (const name of ["OpsqaiDatabase.out.log", "OpsqaiDatabase.err.log", "OpsqaiDatabase.wrapper.log"]) {
    const p = path.join(programData("logs"), name);
    const t = tailFile(p);
    if (t) {
      console.error(`[bootstrap] ${name}:`);
      console.error(t);
    }
  }
  console.error("[bootstrap] --- end diagnostics ---");
}
function httpsGet(url, ms = 30_000) {
  return new Promise((resolve) => {
    const req = https.get(url, { rejectUnauthorized: false, timeout: ms }, (res) => {
      let body = "";
      res.on("data", (c) => (body += c));
      res.on("end", () => resolve({ status: res.statusCode, body }));
    });
    req.on("error", (e) => resolve({ status: 0, error: e.message }));
    req.on("timeout", () => {
      req.destroy();
      resolve({ status: 0, error: "timeout" });
    });
  });
}

(async function main() {
  // Emit explicit stage markers the wizard renderer keys off (see
  // STAGE_MARKERS in renderer/wizard.js). Order matches the 7 progress rows.
  const stage = (name) => log(`STAGE ${name}`);

  stage("preparing installation");

  // --- 1. Start database ---
  if (dbMode === "embedded" && startServices) {
    // Detect a stale data dir so the operator sees an early warning.
    const pgVersion = path.join(programData("data", "pgsql"), "PG_VERSION");
    const pgConf = path.join(programData("data", "pgsql"), "postgresql.conf");
    if (fs.existsSync(pgVersion) && fs.existsSync(pgConf)) {
      try {
        const raw = fs.readFileSync(pgConf, "utf8");
        if (!raw.includes("# --- OPSQAI ---")) {
          log("WARN: existing pgsql data dir is missing OPSQAI config block — service will repair on start");
        }
      } catch {}
    }

    stage("installing services (winsw)");
    log("starting OpsqaiDatabase (postgres)");
    svcCmd("OpsqaiDatabase", "start");

    const port = config.database.embedded.port;

    const tcpOk = await waitTcp("127.0.0.1", port, 120_000);
    if (!tcpOk) {
      console.error(`[bootstrap] postgres TCP port ${port} not reachable after 120s`);
      dumpDbDiagnostics();
      process.exit(3);
    }
    log(`postgres TCP port ${port} open — running pg_isready`);

    const probe = pgIsReady(port, 30_000);
    if (probe.available && !probe.ready) {
      console.error(
        `[bootstrap] pg_isready never returned 0 (last status=${probe.status}, out='${probe.out}', err='${probe.err}')`,
      );
      dumpDbDiagnostics();
      process.exit(3);
    }
    log(`postgres ready on 127.0.0.1:${port}${probe.available ? ` (${probe.out || "pg_isready ok"})` : " (pg_isready.exe missing; TCP-only)"}`);
  }

  // --- 2. Run app migrations ---
  const migrator = programFiles("app", "server", "migrate.mjs");
  if (fs.existsSync(migrator)) {
    log("running app migrations");
    try {
      execFileSync(programFiles("runtime", "node", "node.exe"), [migrator], {
        stdio: "inherit",
        env: {
          ...process.env,
          OPSQAI_ADMIN_EMAIL: adminEmail,
          OPSQAI_ADMIN_PASSWORD: adminPassword,
          OPSQAI_CONFIG: path.join(programData("config"), "config.json"),
        },
      });
    } catch (e) {
      console.error(`[bootstrap] migrations failed: ${e.message}`);
      process.exit(4);
    }
  } else {
    log(`app migrator not present at ${migrator} — skipping (Phase 2 skeleton)`);
  }

  // --- 2b. Seed initial admin user (argon2id + user_roles) ---
  const seeder = programFiles("app", "server", "admin-seed.mjs");
  if (fs.existsSync(seeder)) {
    log("seeding admin account");
    try {
      execFileSync(programFiles("runtime", "node", "node.exe"), [seeder], {
        stdio: "inherit",
        env: {
          ...process.env,
          OPSQAI_ADMIN_EMAIL: adminEmail,
          OPSQAI_ADMIN_PASSWORD: adminPassword,
          OPSQAI_CONFIG: path.join(programData("config"), "config.json"),
        },
      });
      log("admin seeded");
    } catch (e) {
      console.error(`[bootstrap] admin seed failed: ${e.message}`);
      process.exit(6);
    }
  } else {
    log(`admin seeder not present at ${seeder} — skipping`);
  }

  // --- 3. Start Caddy so it emits the local CA, then trust it ---
  if (startServices) {
    log("starting OpsqaiCaddy");
    svcCmd("OpsqaiCaddy", "start");
    // Caddy writes root.crt within a few seconds of first start.
    const rootCert = programData("certs", "pki", "authorities", "local", "root.crt");
    for (let i = 0; i < 30 && !fs.existsSync(rootCert); i++) {
      await new Promise((r) => setTimeout(r, 1000));
    }
    if (fs.existsSync(rootCert)) {
      try {
        execFileSync("certutil.exe", ["-addstore", "-f", "Root", rootCert], { stdio: "inherit" });
        log("Caddy root CA trusted in LocalMachine\\Root");
      } catch (e) {
        console.warn(`[bootstrap] failed to trust Caddy root: ${e.message}`);
      }
    } else {
      console.warn(
        "[bootstrap] Caddy root CA not produced within 30s — browsers may show a warning",
      );
    }
  }

  // --- 4. Start platform + worker + updater ---
  if (startServices) {
    log("starting OpsqaiPlatform");
    svcCmd("OpsqaiPlatform", "start");
    svcCmd("OpsqaiWorker", "start");
    svcCmd("OpsqaiUpdater", "start");

    // --- 5. Health probe ---
    log("probing https://localhost/health");
    let ok = false;
    for (let i = 0; i < 30; i++) {
      const r = await httpsGet("https://localhost/health", 5000);
      if (r.status && r.status >= 200 && r.status < 500) {
        log(`health OK (HTTP ${r.status}) after ${i + 1}s`);
        ok = true;
        break;
      }
      await new Promise((r) => setTimeout(r, 1000));
    }
    if (!ok) {
      console.error("[bootstrap] health probe failed — check %ProgramData%\\OPSQAI\\logs");
      process.exit(5);
    }
  }

  // --- 6. Register daily backup task (Phase 6) ---
  try {
    const scheduled = programFiles("services", "backup", "scheduled.js");
    const node = programFiles("runtime", "node", "node.exe");
    if (fs.existsSync(scheduled) && fs.existsSync(node)) {
      log("registering scheduled task OPSQAI\\DailyBackup (02:15 daily)");
      execFileSync(
        "schtasks.exe",
        [
          "/Create",
          "/F",
          "/SC",
          "DAILY",
          "/ST",
          "02:15",
          "/RL",
          "HIGHEST",
          "/RU",
          "SYSTEM",
          "/TN",
          "OPSQAI\\DailyBackup",
          "/TR",
          `"${node}" "${scheduled}"`,
        ],
        { stdio: "inherit" },
      );
    } else {
      log("scheduled backup script/node missing — skipping schtasks registration");
    }
  } catch (e) {
    console.warn(`[bootstrap] schtasks register failed (non-fatal): ${e.message}`);
  }

  log("done");
})().catch((e) => {
  console.error(`[bootstrap] fatal: ${e.stack || e.message}`);
  process.exit(99);
});
