/**
 * OPSQAI System Documentation Catalog.
 *
 * Single source of truth for auto-generated platform documentation.
 * Every entry maps to a real implemented feature in this codebase.
 * Entries with `featureKey` referencing FEATURE_CATALOG are gated to
 * features that actually ship in the platform.
 */

export interface SystemDocEntry {
  slug: string;
  category: string;
  title: string;
  featureKey?: string; // when set, doc only renders if feature is in FEATURE_CATALOG
  purpose: string;
  whoCanPerform: string[];
  requiredPermissions: string[];
  whenToUse: string;
  steps: string[];
  expectedResult: string;
  commonMistakes: string[];
  tips: string[];
  relatedSlugs: string[];
}

export const SYSTEM_DOC_CATALOG: SystemDocEntry[] = [
  // ───────── Getting Started ─────────
  {
    slug: "getting-started/platform-overview",
    category: "Getting Started",
    title: "Platform Overview",
    purpose:
      "Understand what OPSQAI is, what it does, and how the major modules fit together: Knowledge, AI Assistant, Academy, Workspace, Customer Delivery and Governance.",
    whoCanPerform: ["Everyone"],
    requiredPermissions: ["none"],
    whenToUse:
      "Start here on your first day. Use this overview to orient yourself before opening any other module.",
    steps: [
      "Sign in at /auth using your invited email.",
      "Land on /app — the executive dashboard summarising knowledge, AI activity and gaps.",
      "Open the sidebar to explore Chat, Knowledge, Academy, Workspace, FAQs and Internal Requests.",
      "Admins additionally see Admin (Analytics, Audit Log, Users, AI SOP Generator) and, if granted, Platform.",
      "Use the global search (top of sidebar) to jump to any SOP, FAQ, gap, audit entry, user, thread or workspace in one keystroke.",
    ],
    expectedResult:
      "You can name and locate every module relevant to your role and you understand the difference between Company Knowledge and the OPSQAI platform itself.",
    commonMistakes: [
      "Confusing the Workspace module (private ephemeral AI scratchpad) with the Knowledge module (shared, indexed company knowledge).",
      "Looking for customer documents inside OPSQAI Internal — internal docs are platform-only and never mixed with customer data.",
    ],
    tips: [
      "Bookmark /app — every other page is one click away.",
      "Press the language toggle in the sidebar to switch between EN, DE and RO at any time.",
    ],
    relatedSlugs: ["getting-started/navigation", "getting-started/roles", "getting-started/workspaces"],
  },
  {
    slug: "getting-started/navigation",
    category: "Getting Started",
    title: "Navigation",
    purpose: "Find any feature in OPSQAI in three clicks or fewer.",
    whoCanPerform: ["Everyone"],
    requiredPermissions: ["none"],
    whenToUse: "Use whenever you cannot find a page or want a faster way to reach something you use daily.",
    steps: [
      "The sidebar groups items by Workspace, Admin and Platform — only sections you have permission for appear.",
      "Use Global Search at the top of the sidebar (or press its button) to search across SOPs, FAQs, gaps, users, audit entries and workspaces.",
      "The Workspace Context banner across the top of every page tells platform admins which company they are currently viewing.",
      "The notifications bell shows open knowledge gaps, low-confidence answers and outdated SOPs assigned to you.",
    ],
    expectedResult: "You can navigate between any two pages in OPSQAI without scrolling the sidebar.",
    commonMistakes: [
      "Trying to find admin pages while signed in as a non-admin role — those entries are hidden by design.",
    ],
    tips: ["Global Search is the fastest way to open a single document by name or code."],
    relatedSlugs: ["getting-started/roles", "admin/permissions"],
  },
  {
    slug: "getting-started/workspaces",
    category: "Getting Started",
    title: "Workspace Structure",
    purpose:
      "Understand multi-tenancy: each customer is a workspace, platform admins can switch context, and OPSQAI Internal is the platform's own self-documentation workspace.",
    whoCanPerform: ["Everyone"],
    requiredPermissions: ["none"],
    whenToUse: "Read before working as a platform admin across multiple customers.",
    steps: [
      "Every signed-in user belongs to exactly one company workspace.",
      "Platform Owner and Platform Super Admin see a Workspace switcher in the sidebar to view any company.",
      "Selecting 'All companies (global)' shows aggregated data for platform-level reporting.",
      "OPSQAI Internal is reserved for the platform itself and only ever visible to Platform Owner and Platform Super Admin.",
    ],
    expectedResult:
      "You can confidently switch workspaces, knowing customer data stays isolated and you never accidentally read across companies.",
    commonMistakes: [
      "Editing data while the global view is active — most write actions require a specific workspace to be selected first.",
    ],
    tips: ["The persistent banner at the top of every page tells you which workspace is currently active."],
    relatedSlugs: ["getting-started/roles", "companies/create"],
  },
  {
    slug: "getting-started/roles",
    category: "Getting Started",
    title: "Role Overview",
    purpose:
      "Learn the seven OPSQAI roles and what each can do: Platform Owner, Platform Super Admin, Workspace Owner, Admin, Manager, Team Leader/Supervisor, Employee/Operator.",
    whoCanPerform: ["Everyone"],
    requiredPermissions: ["none"],
    whenToUse: "Before inviting users or troubleshooting permission errors.",
    steps: [
      "Platform Owner: immutable, inherits every permission across every workspace.",
      "Platform Super Admin: full platform powers except cannot remove the Platform Owner.",
      "Workspace Owner / Admin: full powers inside their own company workspace only.",
      "Manager: manages knowledge, gaps, FAQs and training for their workspace.",
      "Team Leader / Supervisor: monitors team activity and reviews answers.",
      "Employee / Operator: asks the AI, reads SOPs, completes training.",
      "Champion: a knowledge contributor empowered by managers to maintain SOPs.",
    ],
    expectedResult: "You understand which role to assign when inviting someone new.",
    commonMistakes: [
      "Assigning Admin when Manager is sufficient — every extra capability widens the audit surface.",
      "Trying to grant Platform roles from inside a customer workspace — only Platform admins can grant Platform roles.",
    ],
    tips: ["Roles are stored in user_roles, never on profiles. This protects against privilege escalation."],
    relatedSlugs: ["users/manage-roles", "admin/permissions"],
  },

  // ───────── Companies ─────────
  {
    slug: "companies/create",
    category: "Company Management",
    title: "Create a Company",
    purpose: "Provision a new customer workspace.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "When onboarding a new paying customer or creating a sandbox for evaluation.",
    steps: [
      "Open Platform → Companies in the sidebar.",
      "Click 'New company'.",
      "Enter the legal name, subscription plan and the maximum number of seats.",
      "Save. A workspace id is generated immediately and isolation is enforced by RLS.",
      "Open the company and invite the first Workspace Owner so they can self-onboard.",
    ],
    expectedResult: "The new company appears in the workspace switcher and you can invite users into it.",
    commonMistakes: [
      "Forgetting to set a sensible max_users — invites will start failing once the quota is reached.",
    ],
    tips: ["Use a recognisable display name (e.g. legal entity + short code) so platform reports stay readable."],
    relatedSlugs: ["companies/edit", "users/invite", "companies/multiple"],
  },
  {
    slug: "companies/edit",
    category: "Company Management",
    title: "Edit Company Information",
    purpose: "Update a workspace's name, plan, retention policy or seat limit.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin", "Workspace Owner"],
    requiredPermissions: ["platform.manage", "workspace.manage"],
    whenToUse: "After a contract change, rename or plan upgrade.",
    steps: [
      "Open Platform → Companies or, for a Workspace Owner, the workspace settings page.",
      "Click the company row to open its detail panel.",
      "Update fields. Changes affecting subscription or seat count are audited.",
      "Save. Active sessions pick up the change on next page load.",
    ],
    expectedResult: "Updated values appear everywhere the company is referenced (sidebar, banner, exports).",
    commonMistakes: ["Lowering max_users below the current active count — new invites will be rejected."],
    tips: ["The Workspace Retention setting controls how long ephemeral AI Workspace files live."],
    relatedSlugs: ["companies/create", "companies/multiple"],
  },
  {
    slug: "companies/multiple",
    category: "Company Management",
    title: "Manage Multiple Companies",
    purpose: "Switch context efficiently when you support several customers.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "Daily, when supporting multiple workspaces from a single account.",
    steps: [
      "Use the Workspace switcher in the sidebar to pick a company.",
      "The banner across the top of every page confirms the active context.",
      "Choose 'All companies (global)' for platform-wide reports such as Companies, Support Inbox and Customer Delivery.",
    ],
    expectedResult: "You can move between workspaces without signing in and out, and you always know which one you're viewing.",
    commonMistakes: [
      "Editing records while in global mode and being surprised when the system asks you to select a specific company.",
    ],
    tips: ["Keep the banner colour in your peripheral vision; it changes when you switch context."],
    relatedSlugs: ["companies/create", "platform/administration"],
  },
  {
    slug: "companies/delete",
    category: "Company Management",
    title: "Delete a Company",
    purpose: "Permanently remove a customer workspace and all its data.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "Only after the customer has been off-boarded, exports are delivered and the retention period has expired.",
    steps: [
      "Export any data the customer needs to keep (see Enterprise Export).",
      "Open Platform → Companies, locate the workspace, click 'Delete' and confirm twice.",
      "Cascading deletes remove knowledge, threads, audit entries and academy data for that workspace.",
    ],
    expectedResult: "The workspace and all related rows are removed. The audit log captures the deletion.",
    commonMistakes: ["Deleting before exporting — there is no undo."],
    tips: ["The OPSQAI Internal workspace cannot be deleted by design."],
    relatedSlugs: ["companies/edit", "admin/exports"],
  },

  // ───────── Users ─────────
  {
    slug: "users/invite",
    category: "User Management",
    title: "Invite Users",
    purpose: "Give a colleague access to a workspace.",
    whoCanPerform: ["Workspace Owner", "Admin", "Manager (limited)", "Platform Admin"],
    requiredPermissions: ["user.create"],
    whenToUse: "Whenever someone needs access. OPSQAI is invite-only by design.",
    steps: [
      "Open Admin → Users.",
      "Click 'Invite user'.",
      "Enter email, first/last name, role and department.",
      "Send. The invitee receives an email with a sign-up link scoped to your workspace.",
      "After they sign up they automatically inherit the invited role and company.",
    ],
    expectedResult: "The user appears in the Users list and can sign in immediately.",
    commonMistakes: [
      "Inviting with the wrong role and then trying to escalate — change the role afterwards rather than re-inviting.",
    ],
    tips: ["Use Departments to pre-route knowledge and gap notifications to the right team."],
    relatedSlugs: ["users/manage-roles", "users/remove", "users/reset"],
  },
  {
    slug: "users/manage-roles",
    category: "User Management",
    title: "Managing Roles",
    purpose: "Promote, demote or change a user's role within a workspace.",
    whoCanPerform: ["Workspace Owner", "Admin", "Platform Admin"],
    requiredPermissions: ["user.update"],
    whenToUse: "Promotion, reorganisation, or when a role was set incorrectly during invite.",
    steps: [
      "Admin → Users → click the user.",
      "Update the role from the dropdown. Multiple roles may be granted; the union of permissions applies.",
      "Save. The change is captured in the Audit Log.",
    ],
    expectedResult: "The user's effective permissions update on their next page load.",
    commonMistakes: [
      "Granting Platform Owner — that role is immutable and bound to the allow-list; it cannot be assigned via UI.",
    ],
    tips: ["Prefer Manager over Admin when only knowledge or gap responsibilities are needed."],
    relatedSlugs: ["users/invite", "admin/permissions"],
  },
  {
    slug: "users/remove",
    category: "User Management",
    title: "Remove a User",
    purpose: "Revoke access for a leaver.",
    whoCanPerform: ["Workspace Owner", "Admin", "Platform Admin"],
    requiredPermissions: ["user.delete"],
    whenToUse: "When someone leaves the organisation or no longer needs access.",
    steps: [
      "Admin → Users → click the user.",
      "Choose 'Remove from workspace'.",
      "Confirm. Their auth session is invalidated and they lose access to all workspace data.",
    ],
    expectedResult: "The user can no longer sign in to that workspace; historic audit entries are preserved.",
    commonMistakes: ["Removing a user before transferring ownership of their gaps or assigned training."],
    tips: ["Re-invite later if needed — historic audit entries link by user id."],
    relatedSlugs: ["users/invite", "users/reset"],
  },
  {
    slug: "users/reset",
    category: "User Management",
    title: "Reset User Access",
    purpose: "Help a user who has lost access or been locked out.",
    whoCanPerform: ["Workspace Owner", "Admin", "Platform Admin"],
    requiredPermissions: ["user.update"],
    whenToUse: "Forgotten password, MFA reset, or session issues.",
    steps: [
      "Ask the user to use 'Forgot password' at /auth — most cases resolve themselves.",
      "If unresolved, open Admin → Users and trigger a magic-link or password reset email.",
      "Audit Log records the reset, including who performed it.",
    ],
    expectedResult: "The user receives a recovery email and can regain access.",
    commonMistakes: ["Sharing passwords manually — always trigger a self-service reset."],
    tips: ["For SSO customers, password resets happen at the identity provider, not here."],
    relatedSlugs: ["users/remove", "admin/audit-log"],
  },

  // ───────── Knowledge ─────────
  {
    slug: "knowledge/create-article",
    category: "Knowledge Management",
    featureKey: "knowledge_base",
    title: "Create a Knowledge Article",
    purpose: "Add a new SOP, policy or how-to into the workspace knowledge base.",
    whoCanPerform: ["Admin", "Manager", "Champion"],
    requiredPermissions: ["knowledge.manage", "sop.edit"],
    whenToUse: "When a topic the assistant should know about is missing from the KB.",
    steps: [
      "Open Knowledge.",
      "Click 'New document', set title, category, department and doc code.",
      "Paste or write the body. Markdown formatting is supported.",
      "Save. The system splits the content into chunks and embeds them for semantic search.",
      "Confirm the status pill switches from 'processing' to 'ready'.",
    ],
    expectedResult: "The article appears in Knowledge, is searchable, and the AI Assistant can cite it.",
    commonMistakes: [
      "Pasting an entire 100-page document into one article instead of splitting by topic.",
      "Forgetting to set a doc code — citations look cleaner with codes like SOP-WH-01.",
    ],
    tips: [
      "Short, focused articles (1–3 pages) retrieve more reliably than monolithic documents.",
      "Mark business-critical SOPs with the Critical flag to surface them on the dashboard.",
    ],
    relatedSlugs: ["knowledge/upload", "knowledge/publish", "knowledge/versions"],
  },
  {
    slug: "knowledge/upload",
    category: "Knowledge Management",
    featureKey: "knowledge_base",
    title: "Upload Documents",
    purpose: "Bring existing PDF, DOCX, PPTX, XLSX or text files into the KB.",
    whoCanPerform: ["Admin", "Manager", "Champion"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "Onboarding from a SharePoint or shared-drive based knowledge base.",
    steps: [
      "Knowledge → Upload.",
      "Drag in one or more files; the server extracts text on the server side.",
      "Set department and category metadata.",
      "Save. The pipeline chunks the text and writes embeddings; large documents may take a minute.",
    ],
    expectedResult: "The document shows status 'ready' with a chunk count > 0 and is retrievable from chat.",
    commonMistakes: ["Uploading scanned PDFs without OCR — they extract no text and the AI cannot use them."],
    tips: ["Re-run extraction (Reprocess) if a document was uploaded before its source format was supported."],
    relatedSlugs: ["knowledge/create-article", "knowledge/publish"],
  },
  {
    slug: "knowledge/publish",
    category: "Knowledge Management",
    featureKey: "knowledge_base",
    title: "Publish Documents",
    purpose: "Make an article visible to all members of the workspace.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "After review and approval.",
    steps: [
      "Open the document in Knowledge.",
      "Toggle 'Active' on.",
      "Optionally mark as Critical so it appears on the dashboard.",
    ],
    expectedResult: "The document is included in retrieval results for everyone in the workspace.",
    commonMistakes: ["Publishing drafts that contain placeholders or unverified procedures."],
    tips: ["Use Acknowledgements to require operators to confirm they have read critical SOPs."],
    relatedSlugs: ["knowledge/create-article", "knowledge/archive", "knowledge/versions"],
  },
  {
    slug: "knowledge/archive",
    category: "Knowledge Management",
    featureKey: "knowledge_base",
    title: "Archive Documents",
    purpose: "Remove outdated content from retrieval without losing history.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "When a procedure is replaced or no longer valid.",
    steps: [
      "Open the document.",
      "Toggle 'Active' off (or upload a new version which auto-supersedes the old one).",
      "The chunk index is retained so historic audit entries still resolve.",
    ],
    expectedResult: "The document no longer appears in chat citations or KB browsing for end users.",
    commonMistakes: ["Hard-deleting instead of archiving and losing the audit trail."],
    tips: ["Add a brief change note explaining why it was archived."],
    relatedSlugs: ["knowledge/publish", "knowledge/versions"],
  },
  {
    slug: "knowledge/versions",
    category: "Knowledge Management",
    featureKey: "sop_versioning",
    title: "Manage Versions",
    purpose: "Track who changed what, when and why.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["sop.edit", "knowledge.manage"],
    whenToUse: "Whenever an SOP is revised.",
    steps: [
      "Open the document and click 'New version'.",
      "Edit the body and add a short change note.",
      "Save. The prior version is preserved with its own embedding index.",
    ],
    expectedResult: "A version history is visible and the latest version is the one retrieved by chat.",
    commonMistakes: ["Editing in place without bumping the version — change notes are lost."],
    tips: ["The Audit Log captures every version transition with old and new content."],
    relatedSlugs: ["knowledge/publish", "admin/audit-log"],
  },

  // ───────── AI features ─────────
  {
    slug: "ai/chat",
    category: "AI Features",
    featureKey: "ai_assistant",
    title: "AI Chat",
    purpose: "Ask the assistant any operational question and get a sourced answer.",
    whoCanPerform: ["Everyone (chat.use)"],
    requiredPermissions: ["chat.use"],
    whenToUse: "Daily — the assistant is the fastest path to a procedure or policy.",
    steps: [
      "Open Chat (sidebar).",
      "Type your question in your preferred language (DE, EN, RO, and more are auto-detected).",
      "Read the answer; expand the Sources block to verify the citation.",
      "Use follow-up questions to drill in — context carries inside the thread.",
    ],
    expectedResult: "A concise answer grounded in the company KB plus citations to the documents used.",
    commonMistakes: [
      "Treating the assistant as ChatGPT — OPSQAI refuses anything it cannot ground in the KB.",
      "Asking compound questions; break them into shorter follow-ups for cleaner citations.",
    ],
    tips: ["Click 'Create Internal Request' on a refusal to trigger the Knowledge Gap workflow."],
    relatedSlugs: ["ai/confidence", "ai/knowledge-gaps", "knowledge/create-article"],
  },
  {
    slug: "ai/audit",
    category: "AI Features",
    featureKey: "ai_workspace_audit",
    title: "AI Workspace Audit",
    purpose: "Score the readiness of a customer workspace and get a roadmap.",
    whoCanPerform: ["Admin", "Manager", "Platform Admin"],
    requiredPermissions: ["ai_audit.run"],
    whenToUse: "Quarterly, or before a customer business review.",
    steps: [
      "Open Admin → AI Workspace Audit.",
      "Click 'Run audit'. The engine inspects documents, gaps, training and activity.",
      "Read the executive summary and the recommendations.",
      "Export a PDF for the customer.",
    ],
    expectedResult: "A maturity score (0–100), a written summary and a prioritised action list.",
    commonMistakes: ["Running an audit before any content is uploaded — the score will be artificially low."],
    tips: ["Compare audit scores quarter over quarter to demonstrate progress."],
    relatedSlugs: ["admin/dashboard", "ai/knowledge-gaps"],
  },
  {
    slug: "ai/teacher",
    category: "AI Features",
    featureKey: "academy",
    title: "AI Teacher",
    purpose: "Deliver lesson explanations and answer learner questions during training.",
    whoCanPerform: ["Everyone (academy.learn)"],
    requiredPermissions: ["academy.learn"],
    whenToUse: "Inside an Academy lesson when the learner asks a question.",
    steps: [
      "Open a lesson from Academy → My Courses.",
      "Ask a question in the lesson chat.",
      "The Teacher answers using the lesson's source documents and the KB only.",
      "Take the quiz to unlock the next chapter.",
    ],
    expectedResult: "The learner receives grounded, lesson-scoped explanations and progresses through the path.",
    commonMistakes: ["Expecting the Teacher to invent material — it stays within the lesson source documents."],
    tips: ["The Teacher answers in the learner's chosen language automatically."],
    relatedSlugs: ["academy/learning-paths", "academy/quiz"],
  },
  {
    slug: "ai/knowledge-gaps",
    category: "AI Features",
    featureKey: "knowledge_gaps",
    title: "Knowledge Gaps",
    purpose: "Capture every question the AI could not answer and turn each into new KB content.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "Weekly review of the Gaps inbox.",
    steps: [
      "Open Admin → Knowledge Gaps.",
      "Sort by Occurrences to focus on the most-asked unanswered questions.",
      "Open a gap, write or upload an answer, then promote it into the KB.",
      "The gap is closed automatically once a covering document is published.",
    ],
    expectedResult: "Coverage improves over time; the same question stops appearing in the gaps inbox.",
    commonMistakes: ["Closing gaps without publishing — they will re-open the next time someone asks."],
    tips: ["Use the AI SOP Generator to draft an answer in seconds, then refine it."],
    relatedSlugs: ["ai/sop-generator", "knowledge/create-article", "requests/create"],
  },
  {
    slug: "ai/sop-generator",
    category: "AI Features",
    featureKey: "ai_sop_generator",
    title: "AI SOP Generator",
    purpose: "Draft a structured SOP from a short brief.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["sop.generate"],
    whenToUse: "When a knowledge gap needs a new SOP and you want a quality first draft.",
    steps: [
      "Open Admin → AI SOP Generator.",
      "Provide a topic, target audience and key constraints.",
      "Click 'Generate'.",
      "Review the draft, edit, then publish to Knowledge.",
    ],
    expectedResult: "A professionally structured SOP draft ready for human review.",
    commonMistakes: ["Publishing without review — always validate facts against your operational reality."],
    tips: ["Generated SOPs are tagged so reviewers know they came from the generator."],
    relatedSlugs: ["knowledge/create-article", "ai/knowledge-gaps"],
  },
  {
    slug: "ai/document-review",
    category: "AI Features",
    featureKey: "ai_workspace",
    title: "Document Review",
    purpose: "Use the AI Workspace to summarise, compare or extract risks from temporary files.",
    whoCanPerform: ["Manager", "Admin"],
    requiredPermissions: ["workspace.use"],
    whenToUse: "When you need AI help on a one-off document that should NOT become part of the KB.",
    steps: [
      "Open Workspace → New workspace.",
      "Upload PDFs, DOCX or XLSX files.",
      "Ask the assistant to summarise, extract KPIs, compare versions or find risks.",
      "Files auto-delete per your workspace retention policy.",
    ],
    expectedResult: "You get answers about your uploaded documents without polluting the company KB.",
    commonMistakes: ["Treating Workspace as KB — uploaded files are isolated and never searchable from chat."],
    tips: ["Generated artifacts (PPTX, XLSX, DOCX, PDF) follow the same retention policy."],
    relatedSlugs: ["ai/chat", "admin/workspace-settings"],
  },
  {
    slug: "ai/confidence",
    category: "AI Features",
    featureKey: "confidence_scoring",
    title: "Confidence Scores",
    purpose: "Understand how certain the assistant is about each answer.",
    whoCanPerform: ["Everyone"],
    requiredPermissions: ["chat.use"],
    whenToUse: "When deciding whether to trust an answer or escalate.",
    steps: [
      "Look at the confidence badge attached to the assistant's reply.",
      "High = strong source match. Medium = some uncertainty. Low = treat with caution and verify.",
      "Below the per-workspace threshold (default 55%), managers receive a notification for review.",
    ],
    expectedResult: "You can quickly assess answer quality without reading the entire source.",
    commonMistakes: ["Acting on a low-confidence answer for a safety-critical task without verification."],
    tips: ["Tune the threshold per workspace if your team needs stricter or looser controls."],
    relatedSlugs: ["ai/chat", "ai/knowledge-gaps"],
  },

  // ───────── Academy ─────────
  {
    slug: "academy/create-course",
    category: "Academy",
    featureKey: "academy",
    title: "Create Courses",
    purpose: "Build a structured learning path from existing SOPs.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["academy.manage"],
    whenToUse: "When onboarding a department or rolling out a critical procedure.",
    steps: [
      "Open Admin → Academy Manager.",
      "Create a Department, then a Learning Path inside it.",
      "Add Chapters and Lessons; attach source documents from Knowledge.",
      "Generate lesson content with the built-in AI authoring tool.",
      "Publish.",
    ],
    expectedResult: "Learners in the assigned department see the new path under My Courses.",
    commonMistakes: ["Building courses on top of unpublished knowledge — the AI Teacher cannot read it."],
    tips: ["Re-using a single SOP across multiple paths keeps content consistent."],
    relatedSlugs: ["academy/assign", "academy/learning-paths", "academy/quiz"],
  },
  {
    slug: "academy/assign",
    category: "Academy",
    featureKey: "academy",
    title: "Assign Training",
    purpose: "Enrol users into a learning path.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["academy.manage"],
    whenToUse: "On hire, on role change, or when a path is published.",
    steps: [
      "Open the Learning Path.",
      "Use 'Assign' to enrol individuals or whole departments.",
      "Set a due date if needed.",
    ],
    expectedResult: "Enrolled users see the path in My Courses and start receiving reminders.",
    commonMistakes: ["Setting unrealistic due dates that produce noisy notifications."],
    tips: ["Track completion with the Analytics tab inside Academy."],
    relatedSlugs: ["academy/learning-paths", "academy/create-course"],
  },
  {
    slug: "academy/learning-paths",
    category: "Academy",
    featureKey: "academy",
    title: "Learning Paths",
    purpose: "Group related chapters and lessons into a complete programme.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["academy.manage"],
    whenToUse: "When designing role-based onboarding (e.g. Picker, Forklift Driver, Supervisor).",
    steps: [
      "Create a Path under a Department.",
      "Add Chapters in the order learners should complete them.",
      "Add Lessons under each Chapter and set the quiz pass threshold.",
    ],
    expectedResult: "A coherent learning journey with predictable structure and assessable outcomes.",
    commonMistakes: ["Mixing audiences in one path — keep paths role-specific for relevance."],
    tips: ["Use chapter-level pass requirements to gate progression."],
    relatedSlugs: ["academy/create-course", "academy/quiz", "academy/certificates"],
  },
  {
    slug: "academy/certificates",
    category: "Academy",
    featureKey: "academy",
    title: "Certificates",
    purpose: "Reward successful completion and provide proof for audits.",
    whoCanPerform: ["Everyone (learners)"],
    requiredPermissions: ["academy.learn"],
    whenToUse: "Automatically issued at path completion.",
    steps: [
      "Complete every chapter and pass the final quiz.",
      "A PDF certificate is generated and stored on your Certificates page.",
      "Share the verification link with auditors; the link uses a public verify endpoint.",
    ],
    expectedResult: "A signed, verifiable PDF certificate per completed path.",
    commonMistakes: ["Re-issuing certificates without revoking the old one — the verify endpoint resolves the latest."],
    tips: ["Certificate verification is read-only and safe to share externally."],
    relatedSlugs: ["academy/learning-paths", "academy/assessments"],
  },
  {
    slug: "academy/quiz",
    category: "Academy",
    featureKey: "academy",
    title: "Quiz Management",
    purpose: "Author lesson quizzes that gate progression.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["academy.manage"],
    whenToUse: "Inside any lesson where comprehension must be verified.",
    steps: [
      "Open the lesson and click 'Edit quiz'.",
      "Add 3–10 questions; set the pass threshold (default 80%).",
      "Publish.",
    ],
    expectedResult: "Learners must pass before the next lesson unlocks.",
    commonMistakes: ["Writing trick questions — quizzes are for comprehension, not gotchas."],
    tips: ["Use the heatmap in Analytics to spot questions everyone fails."],
    relatedSlugs: ["academy/create-course", "academy/assessments"],
  },
  {
    slug: "academy/assessments",
    category: "Academy",
    featureKey: "academy",
    title: "Assessments",
    purpose: "Review attempts, scores and time spent.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["academy.manage"],
    whenToUse: "Reviewing programme effectiveness or coaching individuals.",
    steps: [
      "Open Academy Analytics.",
      "Drill into the path, chapter or lesson of interest.",
      "Inspect failure rates, average score and time-to-complete.",
    ],
    expectedResult: "You can identify weak content and weak learners objectively.",
    commonMistakes: ["Penalising learners for failing badly-written questions — fix the question first."],
    tips: ["Retraining events fire automatically when a source SOP changes."],
    relatedSlugs: ["academy/quiz", "academy/learning-paths"],
  },

  // ───────── Delivery Library ─────────
  {
    slug: "delivery/upload",
    category: "Delivery Library",
    featureKey: "enterprise_export",
    title: "Uploading Deliverables",
    purpose: "Store final consulting deliverables for a customer.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "After a customer engagement milestone.",
    steps: [
      "Open Platform → Enterprise Documents.",
      "Select the customer workspace.",
      "Upload the deliverable into the appropriate category (Commercial, Contracts, Implementation…).",
    ],
    expectedResult: "The file is visible to the customer team and tracked in the timeline.",
    commonMistakes: ["Uploading drafts; this library is for finalised deliverables."],
    tips: ["Generate consulting-style deliverables using the built-in AI writer."],
    relatedSlugs: ["delivery/templates", "delivery/export"],
  },
  {
    slug: "delivery/templates",
    category: "Delivery Library",
    featureKey: "enterprise_export",
    title: "Managing Templates",
    purpose: "Maintain the catalogue of customer deliverable templates.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "When a new offering or document type is introduced.",
    steps: [
      "Edit src/lib/customer-templates.ts (platform release) or add a new entry via the admin tool.",
      "Templates appear in the document generator dropdown immediately after release.",
    ],
    expectedResult: "Consultants can produce branded, on-message documents from a click.",
    commonMistakes: ["Hardcoding customer-specific values into templates — use variables instead."],
    tips: ["Variables auto-fill from the customer profile; missing fields render as 'Not configured'."],
    relatedSlugs: ["delivery/upload", "delivery/export"],
  },
  {
    slug: "delivery/export",
    category: "Delivery Library",
    featureKey: "enterprise_export",
    title: "Exporting Files",
    purpose: "Hand over deliverables in the format the customer wants.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "At engagement close, or anytime the customer requests a copy.",
    steps: [
      "Open Enterprise Documents → Customer.",
      "Select one or many documents.",
      "Click 'Download All (.zip)' or export individually as PDF, DOCX, HTML or Markdown.",
    ],
    expectedResult: "Pixel-quality outputs in the chosen format.",
    commonMistakes: ["Re-running the generator instead of downloading the existing rendered file."],
    tips: ["Use 'Delete All' to clean a workspace between engagements."],
    relatedSlugs: ["delivery/upload", "delivery/templates"],
  },

  // ───────── Requests (Tickets) ─────────
  {
    slug: "requests/create",
    category: "Tickets",
    featureKey: "internal_requests",
    title: "Creating Tickets",
    purpose: "Capture an unanswered question or process change request.",
    whoCanPerform: ["Everyone"],
    requiredPermissions: ["none"],
    whenToUse: "When the assistant refuses, or when something needs an SOP that does not yet exist.",
    steps: [
      "On a refusal, click 'Create Internal Request'.",
      "Or open Internal Requests → New request.",
      "Describe the situation; attach evidence.",
      "Submit.",
    ],
    expectedResult: "A ticket is created, assignees are notified, and the original question is preserved.",
    commonMistakes: ["Filing duplicate requests; check the existing list first."],
    tips: ["Promote a resolved request into the KB so the same question never recurs."],
    relatedSlugs: ["requests/assign", "requests/resolve", "ai/knowledge-gaps"],
  },
  {
    slug: "requests/assign",
    category: "Tickets",
    featureKey: "internal_requests",
    title: "Assigning Tickets",
    purpose: "Route a ticket to the right owner.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "Triage stage.",
    steps: [
      "Open the request.",
      "Set assignee, priority and due date.",
      "Add a triage note.",
    ],
    expectedResult: "Assignee receives a notification and the ticket appears in their queue.",
    commonMistakes: ["Assigning without setting priority — everything ends up tied for first."],
    tips: ["Critical requests escalate via the notification bell automatically."],
    relatedSlugs: ["requests/create", "requests/resolve"],
  },
  {
    slug: "requests/resolve",
    category: "Tickets",
    featureKey: "internal_requests",
    title: "Resolving Tickets",
    purpose: "Close out the work and capture the resolution.",
    whoCanPerform: ["Admin", "Manager", "Assignee"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "When the underlying question or change has been addressed.",
    steps: [
      "Open the request.",
      "Write the resolution and attach references.",
      "Promote to KB if the answer is reusable.",
      "Click 'Resolve'.",
    ],
    expectedResult: "Status switches to Resolved, requester is notified, KB is updated if promoted.",
    commonMistakes: ["Resolving without promoting reusable knowledge — see Knowledge Gaps."],
    tips: ["Resolved requests appear in the Audit Log for traceability."],
    relatedSlugs: ["requests/assign", "ai/knowledge-gaps", "admin/audit-log"],
  },
  {
    slug: "requests/workflow",
    category: "Tickets",
    featureKey: "internal_requests",
    title: "Ticket Workflow",
    purpose: "Understand the full lifecycle: Open → Triaged → In progress → Resolved/Rejected.",
    whoCanPerform: ["Everyone"],
    requiredPermissions: ["none"],
    whenToUse: "Before contributing to a customer's ticket queue.",
    steps: [
      "Open: new request, no owner.",
      "Triaged: assigned with priority and due date.",
      "In progress: owner is actively working on it.",
      "Resolved: closed with a documented outcome.",
      "Rejected: closed without action, with a reason.",
    ],
    expectedResult: "Predictable, auditable handling of every operational question.",
    commonMistakes: ["Skipping triage — unowned tickets stall."],
    tips: ["Each transition is captured in the Audit Log for governance."],
    relatedSlugs: ["requests/create", "requests/assign", "requests/resolve"],
  },

  // ───────── Administration ─────────
  {
    slug: "admin/workspace-settings",
    category: "Administration",
    title: "Workspace Settings",
    purpose: "Configure company-wide preferences such as min confidence and retention.",
    whoCanPerform: ["Workspace Owner", "Admin", "Platform Admin"],
    requiredPermissions: ["workspace.manage"],
    whenToUse: "On setup, and whenever organisational policy changes.",
    steps: [
      "Open Admin (Dashboard) for the workspace.",
      "Adjust the minimum confidence threshold for AI answers.",
      "Set the Workspace retention policy for ephemeral AI files.",
      "Save.",
    ],
    expectedResult: "Settings take effect immediately for everyone in the workspace.",
    commonMistakes: ["Setting retention to 'Manual deletion only' without an associated cleanup process."],
    tips: ["Retention changes only apply to files created after the change."],
    relatedSlugs: ["admin/branding", "admin/notifications", "ai/confidence"],
  },
  {
    slug: "admin/branding",
    category: "Administration",
    featureKey: "brand_center",
    title: "Branding",
    purpose: "Customise logos, palette and typography for the platform.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "Brand refreshes, dark/light theming, custom domains.",
    steps: [
      "Open Admin → Brand Center.",
      "Update logo files, primary/secondary palette and typography.",
      "Preview, then save to apply globally.",
    ],
    expectedResult: "All app surfaces (sidebar, marketing site, exports) pick up the new identity.",
    commonMistakes: ["Uploading logos with insufficient contrast — sidebar uses both light and dark variants."],
    tips: ["Brand Center is platform-wide; customer workspaces can override their logo only."],
    relatedSlugs: ["admin/workspace-settings", "platform/administration"],
  },
  {
    slug: "admin/notifications",
    category: "Administration",
    featureKey: "notifications",
    title: "Notifications",
    purpose: "Choose what triggers in-app and email notifications.",
    whoCanPerform: ["Everyone (own preferences)", "Admin (workspace defaults)"],
    requiredPermissions: ["none"],
    whenToUse: "On invite, and whenever notification volume becomes noisy.",
    steps: [
      "Open Profile → Notifications.",
      "Toggle individual triggers: low confidence answers, new gaps, ticket assignments, outdated SOPs.",
      "Save.",
    ],
    expectedResult: "Notification bell highlights only the events you care about.",
    commonMistakes: ["Disabling notifications entirely — critical workflow events go silent."],
    tips: ["Outdated-SOP notifications fire every 90 days for documents older than 6 months."],
    relatedSlugs: ["admin/workspace-settings", "knowledge/versions"],
  },
  {
    slug: "admin/permissions",
    category: "Administration",
    featureKey: "rbac",
    title: "Permissions",
    purpose: "Understand and adjust what each role can do.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "Reviewing the RBAC matrix or adding a new permission.",
    steps: [
      "Permissions are seeded in the role_permissions table and resolved by has_permission().",
      "Platform Owner inherits every permission via is_platform_owner().",
      "To grant a new permission, add a row in role_permissions; UI gating uses hasPermission().",
    ],
    expectedResult: "Effective permissions match the documented matrix and the principle of least privilege.",
    commonMistakes: [
      "Storing roles on profiles — never do this; it enables privilege escalation. Roles live in user_roles.",
    ],
    tips: ["Use the my_permissions() RPC to inspect what the current user can do."],
    relatedSlugs: ["users/manage-roles", "platform/administration"],
  },
  {
    slug: "admin/audit-log",
    category: "Administration",
    featureKey: "audit_log",
    title: "Audit Log",
    purpose: "Inspect every action performed inside a workspace.",
    whoCanPerform: ["Admin", "Manager", "Platform Admin"],
    requiredPermissions: ["audit.view"],
    whenToUse: "Incident response, compliance reviews, customer questions.",
    steps: [
      "Open Admin → Audit Log.",
      "Filter by user, module, action, severity or date range.",
      "Click a row to view the before/after payload and the resolved sources.",
    ],
    expectedResult: "Complete traceability of who did what, when and with what data.",
    commonMistakes: ["Exporting raw audit data without redacting customer questions before sharing externally."],
    tips: ["Audit entries are immutable from the UI; they can only be archived by retention policy."],
    relatedSlugs: ["admin/permissions", "platform/administration"],
  },
  {
    slug: "admin/exports",
    category: "Administration",
    featureKey: "enterprise_export",
    title: "Enterprise Export",
    purpose: "Export a workspace's data for backup, audit or migration.",
    whoCanPerform: ["Admin", "Platform Admin"],
    requiredPermissions: ["analytics.view"],
    whenToUse: "Quarterly backups, customer off-boarding, regulator requests.",
    steps: [
      "Open Admin → Exports (Reports).",
      "Choose the scope: Knowledge, FAQs, Audit, Gaps, Academy.",
      "Pick a format: ZIP, JSON, CSV or Markdown.",
      "Download once the job completes.",
    ],
    expectedResult: "A self-contained archive of the requested data.",
    commonMistakes: ["Exporting in CSV when nested structures are needed — choose JSON instead."],
    tips: ["Exports are listed under your Reports history for re-download."],
    relatedSlugs: ["companies/delete", "admin/audit-log"],
  },

  // ───────── Platform ─────────
  {
    slug: "platform/administration",
    category: "Platform",
    featureKey: "platform_admin",
    title: "Platform Settings",
    purpose: "Manage anything that crosses customer boundaries.",
    whoCanPerform: ["Platform Owner", "Platform Super Admin"],
    requiredPermissions: ["platform.manage"],
    whenToUse: "Cross-customer reporting, role grants, system-wide configuration.",
    steps: [
      "Open Platform → Platform Administration.",
      "Review platform-wide KPIs.",
      "Manage Platform Super Admins from the dedicated page.",
      "Review Support Inbox to answer customers across companies.",
    ],
    expectedResult: "A single pane of glass for platform operations.",
    commonMistakes: ["Performing customer-scoped actions while in 'All companies' mode."],
    tips: ["The Workspace banner reminds you whether you're in global or per-customer mode."],
    relatedSlugs: ["companies/multiple", "admin/permissions", "admin/audit-log"],
  },

  // ───────── Troubleshooting ─────────
  {
    slug: "troubleshooting/pdf-export",
    category: "Troubleshooting",
    title: "PDF Export Problems",
    purpose: "Recover from failures when exporting documents as PDF.",
    whoCanPerform: ["Admin", "Platform Admin"],
    requiredPermissions: ["none"],
    whenToUse: "When a PDF download throws an error or produces an empty file.",
    steps: [
      "Reload the page and try again — most failures are transient.",
      "If the generator reports 'Cannot destructure ... __extends', the canonical ESM build is missing; raise a platform issue.",
      "For oversized documents, split the source into smaller sections.",
    ],
    expectedResult: "PDF downloads complete with all formatting preserved.",
    commonMistakes: ["Trying to export non-Unicode content; the generator sanitises but extremes still fail."],
    tips: ["DOCX export is available as a fallback for every PDF route."],
    relatedSlugs: ["delivery/export", "admin/exports"],
  },
  {
    slug: "troubleshooting/login",
    category: "Troubleshooting",
    title: "Login Issues",
    purpose: "Help users who cannot sign in.",
    whoCanPerform: ["Admin", "Platform Admin"],
    requiredPermissions: ["user.update"],
    whenToUse: "Sign-in failures, MFA prompts, or magic link issues.",
    steps: [
      "Confirm the email matches an invited user in your workspace.",
      "Trigger a password reset from Admin → Users.",
      "Check that the customer's IdP (if SSO) is reachable.",
    ],
    expectedResult: "The user can sign in within minutes.",
    commonMistakes: ["Creating a second account with a typo'd email — invite is single-use."],
    tips: ["Audit Log → action = login.failed shows the upstream reason."],
    relatedSlugs: ["users/reset", "admin/audit-log"],
  },
  {
    slug: "troubleshooting/search",
    category: "Troubleshooting",
    title: "Search Issues",
    purpose: "Diagnose poor search results.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "When Global Search or chat retrieval misses obvious matches.",
    steps: [
      "Confirm the missing document has status = ready and chunk_count > 0.",
      "Reprocess the document to refresh embeddings if it was uploaded before extraction improvements landed.",
      "Lower the workspace min confidence temporarily to diagnose retrieval vs answer-grounding.",
    ],
    expectedResult: "The expected source appears in retrieval and is cited by the AI.",
    commonMistakes: ["Treating a refusal as a search failure — refusals are intentional for ungrounded answers."],
    tips: ["The chat logs include top similarity scores; check them in the server logs."],
    relatedSlugs: ["knowledge/upload", "ai/confidence", "troubleshooting/ai-problems"],
  },
  {
    slug: "troubleshooting/ai-problems",
    category: "Troubleshooting",
    title: "AI Generation Problems",
    purpose: "Diagnose slow or failing AI responses.",
    whoCanPerform: ["Admin", "Platform Admin"],
    requiredPermissions: ["none"],
    whenToUse: "Slow chat, blank responses, or HTTP 402 errors.",
    steps: [
      "Open the browser network panel and look for /api/chat status codes.",
      "402 = AI gateway credits exhausted; top up via Platform.",
      "5xx = transient gateway failure; retry the message.",
    ],
    expectedResult: "Chat responds within seconds and citations render correctly.",
    commonMistakes: ["Assuming the AI is broken when in fact the KB is empty for the topic."],
    tips: ["The audit log records mode = gap when no sources matched, regardless of model availability."],
    relatedSlugs: ["ai/chat", "ai/confidence", "troubleshooting/search"],
  },
  {
    slug: "troubleshooting/permissions",
    category: "Troubleshooting",
    title: "Permission Issues",
    purpose: "Diagnose 'Forbidden' or missing-menu problems.",
    whoCanPerform: ["Admin", "Platform Admin"],
    requiredPermissions: ["user.update"],
    whenToUse: "When a user reports they cannot see a page they expect.",
    steps: [
      "Confirm the user's roles in Admin → Users.",
      "Inspect their effective permissions via my_permissions() RPC.",
      "Check workspace context — the user may be looking at a different company than they think.",
    ],
    expectedResult: "The user gains the access they require, or the limitation is clearly explained.",
    commonMistakes: ["Granting Admin when a single permission like academy.manage would suffice."],
    tips: ["Permissions are additive across roles, so granting a second role can be the cleanest fix."],
    relatedSlugs: ["admin/permissions", "users/manage-roles"],
  },
  {
    slug: "troubleshooting/indexing",
    category: "Troubleshooting",
    title: "Knowledge Indexing",
    purpose: "Re-index documents stuck in 'processing' or with zero chunks.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "When a document never reaches status = ready.",
    steps: [
      "Open the document.",
      "Click 'Reprocess' to re-extract and re-embed.",
      "If extraction fails, replace the source with a text-bearing PDF or DOCX.",
    ],
    expectedResult: "Document status switches to ready and chunk_count is greater than zero.",
    commonMistakes: ["Re-uploading instead of reprocessing — you'll create duplicate documents."],
    tips: ["Scanned PDFs need OCR before upload; OPSQAI does not OCR images."],
    relatedSlugs: ["knowledge/upload", "troubleshooting/search"],
  },

  // ───────── Best Practices ─────────
  {
    slug: "best-practices/knowledge-structure",
    category: "Best Practices",
    title: "Knowledge Structure",
    purpose: "Keep the KB lean and retrievable.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "Continuously; reviewed at every quarterly audit.",
    steps: [
      "One SOP per process; avoid catch-all documents.",
      "Use stable doc codes (SOP-WH-01) so citations stay readable.",
      "Categorise by department; tag critical SOPs.",
      "Retire outdated content with archive, not delete.",
    ],
    expectedResult: "Retrieval is precise, citations are clean, and audits surface gaps not noise.",
    commonMistakes: ["Maintaining a 'misc' category — split it as soon as it grows past 10 documents."],
    tips: ["Run an AI Workspace Audit quarterly to identify structural debt."],
    relatedSlugs: ["knowledge/create-article", "ai/audit"],
  },
  {
    slug: "best-practices/training",
    category: "Best Practices",
    title: "Building Training",
    purpose: "Design Academy paths people actually finish.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["academy.manage"],
    whenToUse: "Whenever a new role-based programme is needed.",
    steps: [
      "Keep paths short: 4–8 lessons, 10–15 minutes each.",
      "Ground every lesson in a real SOP from the KB.",
      "Use quizzes for comprehension, not surveillance.",
    ],
    expectedResult: "High completion rates and measurable competency uplift.",
    commonMistakes: ["Re-using marketing decks as lessons — they don't teach procedure."],
    tips: ["Watch the analytics heatmap for lessons with high failure rates and rewrite them."],
    relatedSlugs: ["academy/create-course", "academy/quiz"],
  },
  {
    slug: "best-practices/audits",
    category: "Best Practices",
    title: "Running Audits",
    purpose: "Use AI Workspace Audit to drive a quarterly cycle.",
    whoCanPerform: ["Admin", "Platform Admin"],
    requiredPermissions: ["ai_audit.run"],
    whenToUse: "Every quarter, and before major customer reviews.",
    steps: [
      "Run the audit at the start of the quarter.",
      "Pick the top three recommendations and assign owners as tickets.",
      "Close the loop at the next audit by comparing scores.",
    ],
    expectedResult: "Measurable, customer-visible improvement in workspace maturity.",
    commonMistakes: ["Treating the audit as a one-off — value comes from the trend."],
    tips: ["Export audits as PDF and attach them to QBR decks."],
    relatedSlugs: ["ai/audit", "admin/exports"],
  },
  {
    slug: "best-practices/managing-ai",
    category: "Best Practices",
    title: "Managing AI",
    purpose: "Keep the AI assistant trustworthy.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["knowledge.manage"],
    whenToUse: "Continuously.",
    steps: [
      "Review the Gaps inbox weekly.",
      "Review low-confidence answers monthly.",
      "Tune the confidence threshold if false-refusals are too frequent.",
    ],
    expectedResult: "The assistant earns trust as a primary information source.",
    commonMistakes: ["Editing the prompt instead of fixing the underlying KB content."],
    tips: ["Confidence + Source-grounded answering is a system property — both must hold."],
    relatedSlugs: ["ai/confidence", "ai/knowledge-gaps", "ai/chat"],
  },
  {
    slug: "best-practices/document-lifecycle",
    category: "Best Practices",
    title: "Document Lifecycle",
    purpose: "Create → review → publish → version → archive.",
    whoCanPerform: ["Admin", "Manager"],
    requiredPermissions: ["sop.edit", "knowledge.manage"],
    whenToUse: "For every SOP, every time.",
    steps: [
      "Create a draft with a clear author and reviewer.",
      "Publish only after explicit review.",
      "Version on every meaningful change; record change notes.",
      "Archive (do not delete) when superseded.",
    ],
    expectedResult: "A defensible audit trail for every operational instruction in the company.",
    commonMistakes: ["Skipping change notes — they are the cheapest documentation you'll write."],
    tips: ["Acknowledgements record that operators have read critical SOP changes."],
    relatedSlugs: ["knowledge/versions", "knowledge/publish", "knowledge/archive"],
  },
];

export type SystemDocCategory = (typeof SYSTEM_DOC_CATALOG)[number]["category"];
