/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as LegalRouteRouteImport } from './routes/legal/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as TrustSecurityArchitectureRouteImport } from './routes/trust.security-architecture'
import { Route as TrustResponsibleAiRouteImport } from './routes/trust.responsible-ai'
import { Route as TrustMultiTenantIsolationRouteImport } from './routes/trust.multi-tenant-isolation'
import { Route as TrustIso27001RoadmapRouteImport } from './routes/trust.iso-27001-roadmap'
import { Route as TrustIncidentResponseRouteImport } from './routes/trust.incident-response'
import { Route as TrustGdprRouteImport } from './routes/trust.gdpr'
import { Route as TrustEncryptionRouteImport } from './routes/trust.encryption'
import { Route as TrustDataRetentionRouteImport } from './routes/trust.data-retention'
import { Route as TrustBackupPolicyRouteImport } from './routes/trust.backup-policy'
import { Route as TrustAvailabilityRouteImport } from './routes/trust.availability'
import { Route as TrustAuditLogsRouteImport } from './routes/trust.audit-logs'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalResponsibleAiRouteImport } from './routes/legal/responsible-ai'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalImpressumRouteImport } from './routes/legal/impressum'
import { Route as LegalDpaRouteImport } from './routes/legal/dpa'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiWorkspaceChatRouteImport } from './routes/api/workspace-chat'
import { Route as ApiInternalChatRouteImport } from './routes/api/internal-chat'
import { Route as ApiDemoChatRouteImport } from './routes/api/demo-chat'
import { Route as ApiCustomerWriterRouteImport } from './routes/api/customer-writer'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAcademyChatRouteImport } from './routes/api/academy-chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAppRequestsRouteImport } from './routes/_authenticated/app.requests'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppKnowledgeRouteImport } from './routes/_authenticated/app.knowledge'
import { Route as AuthenticatedAppInternalRouteImport } from './routes/_authenticated/app.internal'
import { Route as AuthenticatedAppFaqRouteImport } from './routes/_authenticated/app.faq'
import { Route as AuthenticatedAppBrandRouteImport } from './routes/_authenticated/app.brand'
import { Route as AuthenticatedAppWorkspaceIndexRouteImport } from './routes/_authenticated/app.workspace.index'
import { Route as AuthenticatedAppInternalIndexRouteImport } from './routes/_authenticated/app.internal.index'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/app.chat.index'
import { Route as AuthenticatedAppAcademyIndexRouteImport } from './routes/_authenticated/app.academy.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAppWorkspaceSessionIdRouteImport } from './routes/_authenticated/app.workspace.$sessionId'
import { Route as AuthenticatedAppInternalKnowledgeRouteImport } from './routes/_authenticated/app.internal.knowledge'
import { Route as AuthenticatedAppInternalAssistantRouteImport } from './routes/_authenticated/app.internal.assistant'
import { Route as AuthenticatedAppChatThreadIdRouteImport } from './routes/_authenticated/app.chat.$threadId'
import { Route as AuthenticatedAppAdminUsersRouteImport } from './routes/_authenticated/app.admin.users'
import { Route as AuthenticatedAppAdminSupportRouteImport } from './routes/_authenticated/app.admin.support'
import { Route as AuthenticatedAppAdminSopGeneratorRouteImport } from './routes/_authenticated/app.admin.sop-generator'
import { Route as AuthenticatedAppAdminPlatformAdminsRouteImport } from './routes/_authenticated/app.admin.platform-admins'
import { Route as AuthenticatedAppAdminPlatformRouteImport } from './routes/_authenticated/app.admin.platform'
import { Route as AuthenticatedAppAdminKnowledgeGapsRouteImport } from './routes/_authenticated/app.admin.knowledge-gaps'
import { Route as AuthenticatedAppAdminDashboardRouteImport } from './routes/_authenticated/app.admin.dashboard'
import { Route as AuthenticatedAppAdminCustomersRouteImport } from './routes/_authenticated/app.admin.customers'
import { Route as AuthenticatedAppAdminCompaniesRouteImport } from './routes/_authenticated/app.admin.companies'
import { Route as AuthenticatedAppAdminAuditRouteImport } from './routes/_authenticated/app.admin.audit'
import { Route as AuthenticatedAppAdminAnalyticsRouteImport } from './routes/_authenticated/app.admin.analytics'
import { Route as AuthenticatedAppAdminAiAuditRouteImport } from './routes/_authenticated/app.admin.ai-audit'
import { Route as AuthenticatedAppAdminAcademyRouteImport } from './routes/_authenticated/app.admin.academy'
import { Route as AuthenticatedAppAcademySettingsRouteImport } from './routes/_authenticated/app.academy.settings'
import { Route as AuthenticatedAppAcademyKbRouteImport } from './routes/_authenticated/app.academy.kb'
import { Route as AuthenticatedAppAcademyCoursesRouteImport } from './routes/_authenticated/app.academy.courses'
import { Route as AuthenticatedAppAcademyCertificatesRouteImport } from './routes/_authenticated/app.academy.certificates'
import { Route as AuthenticatedAppAcademyAnalyticsRouteImport } from './routes/_authenticated/app.academy.analytics'
import { Route as AuthenticatedAppInternalKnowledgeSlugRouteImport } from './routes/_authenticated/app.internal.knowledge.$slug'
import { Route as AuthenticatedAppAcademyPathPathIdRouteImport } from './routes/_authenticated/app.academy.path.$pathId'
import { Route as AuthenticatedAppAcademyLessonLessonIdRouteImport } from './routes/_authenticated/app.academy.lesson.$lessonId'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustSecurityArchitectureRoute =
  TrustSecurityArchitectureRouteImport.update({
    id: '/security-architecture',
    path: '/security-architecture',
    getParentRoute: () => TrustRoute,
  } as any)
const TrustResponsibleAiRoute = TrustResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => TrustRoute,
} as any)
const TrustMultiTenantIsolationRoute =
  TrustMultiTenantIsolationRouteImport.update({
    id: '/multi-tenant-isolation',
    path: '/multi-tenant-isolation',
    getParentRoute: () => TrustRoute,
  } as any)
const TrustIso27001RoadmapRoute = TrustIso27001RoadmapRouteImport.update({
  id: '/iso-27001-roadmap',
  path: '/iso-27001-roadmap',
  getParentRoute: () => TrustRoute,
} as any)
const TrustIncidentResponseRoute = TrustIncidentResponseRouteImport.update({
  id: '/incident-response',
  path: '/incident-response',
  getParentRoute: () => TrustRoute,
} as any)
const TrustGdprRoute = TrustGdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => TrustRoute,
} as any)
const TrustEncryptionRoute = TrustEncryptionRouteImport.update({
  id: '/encryption',
  path: '/encryption',
  getParentRoute: () => TrustRoute,
} as any)
const TrustDataRetentionRoute = TrustDataRetentionRouteImport.update({
  id: '/data-retention',
  path: '/data-retention',
  getParentRoute: () => TrustRoute,
} as any)
const TrustBackupPolicyRoute = TrustBackupPolicyRouteImport.update({
  id: '/backup-policy',
  path: '/backup-policy',
  getParentRoute: () => TrustRoute,
} as any)
const TrustAvailabilityRoute = TrustAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => TrustRoute,
} as any)
const TrustAuditLogsRoute = TrustAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => TrustRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalResponsibleAiRoute = LegalResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRouteRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceChatRoute = ApiWorkspaceChatRouteImport.update({
  id: '/api/workspace-chat',
  path: '/api/workspace-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatRoute = ApiInternalChatRouteImport.update({
  id: '/api/internal-chat',
  path: '/api/internal-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoChatRoute = ApiDemoChatRouteImport.update({
  id: '/api/demo-chat',
  path: '/api/demo-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerWriterRoute = ApiCustomerWriterRouteImport.update({
  id: '/api/customer-writer',
  path: '/api/customer-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademyChatRoute = ApiAcademyChatRouteImport.update({
  id: '/api/academy-chat',
  path: '/api/academy-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRequestsRoute =
  AuthenticatedAppRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppKnowledgeRoute =
  AuthenticatedAppKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInternalRoute =
  AuthenticatedAppInternalRouteImport.update({
    id: '/internal',
    path: '/internal',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFaqRoute = AuthenticatedAppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBrandRoute = AuthenticatedAppBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWorkspaceIndexRoute =
  AuthenticatedAppWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInternalIndexRoute =
  AuthenticatedAppInternalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInternalRoute,
  } as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyIndexRoute =
  AuthenticatedAppAcademyIndexRouteImport.update({
    id: '/academy/',
    path: '/academy/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWorkspaceSessionIdRoute =
  AuthenticatedAppWorkspaceSessionIdRouteImport.update({
    id: '/workspace/$sessionId',
    path: '/workspace/$sessionId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInternalKnowledgeRoute =
  AuthenticatedAppInternalKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAppInternalRoute,
  } as any)
const AuthenticatedAppInternalAssistantRoute =
  AuthenticatedAppInternalAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppInternalRoute,
  } as any)
const AuthenticatedAppChatThreadIdRoute =
  AuthenticatedAppChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminUsersRoute =
  AuthenticatedAppAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminSupportRoute =
  AuthenticatedAppAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminSopGeneratorRoute =
  AuthenticatedAppAdminSopGeneratorRouteImport.update({
    id: '/admin/sop-generator',
    path: '/admin/sop-generator',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminPlatformAdminsRoute =
  AuthenticatedAppAdminPlatformAdminsRouteImport.update({
    id: '/admin/platform-admins',
    path: '/admin/platform-admins',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminPlatformRoute =
  AuthenticatedAppAdminPlatformRouteImport.update({
    id: '/admin/platform',
    path: '/admin/platform',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminKnowledgeGapsRoute =
  AuthenticatedAppAdminKnowledgeGapsRouteImport.update({
    id: '/admin/knowledge-gaps',
    path: '/admin/knowledge-gaps',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminDashboardRoute =
  AuthenticatedAppAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminCustomersRoute =
  AuthenticatedAppAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminCompaniesRoute =
  AuthenticatedAppAdminCompaniesRouteImport.update({
    id: '/admin/companies',
    path: '/admin/companies',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminAuditRoute =
  AuthenticatedAppAdminAuditRouteImport.update({
    id: '/admin/audit',
    path: '/admin/audit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminAnalyticsRoute =
  AuthenticatedAppAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminAiAuditRoute =
  AuthenticatedAppAdminAiAuditRouteImport.update({
    id: '/admin/ai-audit',
    path: '/admin/ai-audit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminAcademyRoute =
  AuthenticatedAppAdminAcademyRouteImport.update({
    id: '/admin/academy',
    path: '/admin/academy',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademySettingsRoute =
  AuthenticatedAppAcademySettingsRouteImport.update({
    id: '/academy/settings',
    path: '/academy/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyKbRoute =
  AuthenticatedAppAcademyKbRouteImport.update({
    id: '/academy/kb',
    path: '/academy/kb',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyCoursesRoute =
  AuthenticatedAppAcademyCoursesRouteImport.update({
    id: '/academy/courses',
    path: '/academy/courses',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyCertificatesRoute =
  AuthenticatedAppAcademyCertificatesRouteImport.update({
    id: '/academy/certificates',
    path: '/academy/certificates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyAnalyticsRoute =
  AuthenticatedAppAcademyAnalyticsRouteImport.update({
    id: '/academy/analytics',
    path: '/academy/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInternalKnowledgeSlugRoute =
  AuthenticatedAppInternalKnowledgeSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAppInternalKnowledgeRoute,
  } as any)
const AuthenticatedAppAcademyPathPathIdRoute =
  AuthenticatedAppAcademyPathPathIdRouteImport.update({
    id: '/academy/path/$pathId',
    path: '/academy/path/$pathId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyLessonLessonIdRoute =
  AuthenticatedAppAcademyLessonLessonIdRouteImport.update({
    id: '/academy/lesson/$lessonId',
    path: '/academy/lesson/$lessonId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/trust': typeof TrustRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/academy-chat': typeof ApiAcademyChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/customer-writer': typeof ApiCustomerWriterRoute
  '/api/demo-chat': typeof ApiDemoChatRoute
  '/api/internal-chat': typeof ApiInternalChatRoute
  '/api/workspace-chat': typeof ApiWorkspaceChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/responsible-ai': typeof LegalResponsibleAiRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trust/audit-logs': typeof TrustAuditLogsRoute
  '/trust/availability': typeof TrustAvailabilityRoute
  '/trust/backup-policy': typeof TrustBackupPolicyRoute
  '/trust/data-retention': typeof TrustDataRetentionRoute
  '/trust/encryption': typeof TrustEncryptionRoute
  '/trust/gdpr': typeof TrustGdprRoute
  '/trust/incident-response': typeof TrustIncidentResponseRoute
  '/trust/iso-27001-roadmap': typeof TrustIso27001RoadmapRoute
  '/trust/multi-tenant-isolation': typeof TrustMultiTenantIsolationRoute
  '/trust/responsible-ai': typeof TrustResponsibleAiRoute
  '/trust/security-architecture': typeof TrustSecurityArchitectureRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/app/brand': typeof AuthenticatedAppBrandRoute
  '/app/faq': typeof AuthenticatedAppFaqRoute
  '/app/internal': typeof AuthenticatedAppInternalRouteWithChildren
  '/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/requests': typeof AuthenticatedAppRequestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/academy/analytics': typeof AuthenticatedAppAcademyAnalyticsRoute
  '/app/academy/certificates': typeof AuthenticatedAppAcademyCertificatesRoute
  '/app/academy/courses': typeof AuthenticatedAppAcademyCoursesRoute
  '/app/academy/kb': typeof AuthenticatedAppAcademyKbRoute
  '/app/academy/settings': typeof AuthenticatedAppAcademySettingsRoute
  '/app/admin/academy': typeof AuthenticatedAppAdminAcademyRoute
  '/app/admin/ai-audit': typeof AuthenticatedAppAdminAiAuditRoute
  '/app/admin/analytics': typeof AuthenticatedAppAdminAnalyticsRoute
  '/app/admin/audit': typeof AuthenticatedAppAdminAuditRoute
  '/app/admin/companies': typeof AuthenticatedAppAdminCompaniesRoute
  '/app/admin/customers': typeof AuthenticatedAppAdminCustomersRoute
  '/app/admin/dashboard': typeof AuthenticatedAppAdminDashboardRoute
  '/app/admin/knowledge-gaps': typeof AuthenticatedAppAdminKnowledgeGapsRoute
  '/app/admin/platform': typeof AuthenticatedAppAdminPlatformRoute
  '/app/admin/platform-admins': typeof AuthenticatedAppAdminPlatformAdminsRoute
  '/app/admin/sop-generator': typeof AuthenticatedAppAdminSopGeneratorRoute
  '/app/admin/support': typeof AuthenticatedAppAdminSupportRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/app/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/app/internal/assistant': typeof AuthenticatedAppInternalAssistantRoute
  '/app/internal/knowledge': typeof AuthenticatedAppInternalKnowledgeRouteWithChildren
  '/app/workspace/$sessionId': typeof AuthenticatedAppWorkspaceSessionIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/academy/': typeof AuthenticatedAppAcademyIndexRoute
  '/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/app/internal/': typeof AuthenticatedAppInternalIndexRoute
  '/app/workspace/': typeof AuthenticatedAppWorkspaceIndexRoute
  '/app/academy/lesson/$lessonId': typeof AuthenticatedAppAcademyLessonLessonIdRoute
  '/app/academy/path/$pathId': typeof AuthenticatedAppAcademyPathPathIdRoute
  '/app/internal/knowledge/$slug': typeof AuthenticatedAppInternalKnowledgeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/trust': typeof TrustRouteWithChildren
  '/api/academy-chat': typeof ApiAcademyChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/customer-writer': typeof ApiCustomerWriterRoute
  '/api/demo-chat': typeof ApiDemoChatRoute
  '/api/internal-chat': typeof ApiInternalChatRoute
  '/api/workspace-chat': typeof ApiWorkspaceChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/responsible-ai': typeof LegalResponsibleAiRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trust/audit-logs': typeof TrustAuditLogsRoute
  '/trust/availability': typeof TrustAvailabilityRoute
  '/trust/backup-policy': typeof TrustBackupPolicyRoute
  '/trust/data-retention': typeof TrustDataRetentionRoute
  '/trust/encryption': typeof TrustEncryptionRoute
  '/trust/gdpr': typeof TrustGdprRoute
  '/trust/incident-response': typeof TrustIncidentResponseRoute
  '/trust/iso-27001-roadmap': typeof TrustIso27001RoadmapRoute
  '/trust/multi-tenant-isolation': typeof TrustMultiTenantIsolationRoute
  '/trust/responsible-ai': typeof TrustResponsibleAiRoute
  '/trust/security-architecture': typeof TrustSecurityArchitectureRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/app/brand': typeof AuthenticatedAppBrandRoute
  '/app/faq': typeof AuthenticatedAppFaqRoute
  '/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/requests': typeof AuthenticatedAppRequestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/academy/analytics': typeof AuthenticatedAppAcademyAnalyticsRoute
  '/app/academy/certificates': typeof AuthenticatedAppAcademyCertificatesRoute
  '/app/academy/courses': typeof AuthenticatedAppAcademyCoursesRoute
  '/app/academy/kb': typeof AuthenticatedAppAcademyKbRoute
  '/app/academy/settings': typeof AuthenticatedAppAcademySettingsRoute
  '/app/admin/academy': typeof AuthenticatedAppAdminAcademyRoute
  '/app/admin/ai-audit': typeof AuthenticatedAppAdminAiAuditRoute
  '/app/admin/analytics': typeof AuthenticatedAppAdminAnalyticsRoute
  '/app/admin/audit': typeof AuthenticatedAppAdminAuditRoute
  '/app/admin/companies': typeof AuthenticatedAppAdminCompaniesRoute
  '/app/admin/customers': typeof AuthenticatedAppAdminCustomersRoute
  '/app/admin/dashboard': typeof AuthenticatedAppAdminDashboardRoute
  '/app/admin/knowledge-gaps': typeof AuthenticatedAppAdminKnowledgeGapsRoute
  '/app/admin/platform': typeof AuthenticatedAppAdminPlatformRoute
  '/app/admin/platform-admins': typeof AuthenticatedAppAdminPlatformAdminsRoute
  '/app/admin/sop-generator': typeof AuthenticatedAppAdminSopGeneratorRoute
  '/app/admin/support': typeof AuthenticatedAppAdminSupportRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/app/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/app/internal/assistant': typeof AuthenticatedAppInternalAssistantRoute
  '/app/internal/knowledge': typeof AuthenticatedAppInternalKnowledgeRouteWithChildren
  '/app/workspace/$sessionId': typeof AuthenticatedAppWorkspaceSessionIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/academy': typeof AuthenticatedAppAcademyIndexRoute
  '/app/chat': typeof AuthenticatedAppChatIndexRoute
  '/app/internal': typeof AuthenticatedAppInternalIndexRoute
  '/app/workspace': typeof AuthenticatedAppWorkspaceIndexRoute
  '/app/academy/lesson/$lessonId': typeof AuthenticatedAppAcademyLessonLessonIdRoute
  '/app/academy/path/$pathId': typeof AuthenticatedAppAcademyPathPathIdRoute
  '/app/internal/knowledge/$slug': typeof AuthenticatedAppInternalKnowledgeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/legal': typeof LegalRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/trust': typeof TrustRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/academy-chat': typeof ApiAcademyChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/customer-writer': typeof ApiCustomerWriterRoute
  '/api/demo-chat': typeof ApiDemoChatRoute
  '/api/internal-chat': typeof ApiInternalChatRoute
  '/api/workspace-chat': typeof ApiWorkspaceChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/responsible-ai': typeof LegalResponsibleAiRoute
  '/legal/terms': typeof LegalTermsRoute
  '/trust/audit-logs': typeof TrustAuditLogsRoute
  '/trust/availability': typeof TrustAvailabilityRoute
  '/trust/backup-policy': typeof TrustBackupPolicyRoute
  '/trust/data-retention': typeof TrustDataRetentionRoute
  '/trust/encryption': typeof TrustEncryptionRoute
  '/trust/gdpr': typeof TrustGdprRoute
  '/trust/incident-response': typeof TrustIncidentResponseRoute
  '/trust/iso-27001-roadmap': typeof TrustIso27001RoadmapRoute
  '/trust/multi-tenant-isolation': typeof TrustMultiTenantIsolationRoute
  '/trust/responsible-ai': typeof TrustResponsibleAiRoute
  '/trust/security-architecture': typeof TrustSecurityArchitectureRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/_authenticated/app/brand': typeof AuthenticatedAppBrandRoute
  '/_authenticated/app/faq': typeof AuthenticatedAppFaqRoute
  '/_authenticated/app/internal': typeof AuthenticatedAppInternalRouteWithChildren
  '/_authenticated/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/requests': typeof AuthenticatedAppRequestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/academy/analytics': typeof AuthenticatedAppAcademyAnalyticsRoute
  '/_authenticated/app/academy/certificates': typeof AuthenticatedAppAcademyCertificatesRoute
  '/_authenticated/app/academy/courses': typeof AuthenticatedAppAcademyCoursesRoute
  '/_authenticated/app/academy/kb': typeof AuthenticatedAppAcademyKbRoute
  '/_authenticated/app/academy/settings': typeof AuthenticatedAppAcademySettingsRoute
  '/_authenticated/app/admin/academy': typeof AuthenticatedAppAdminAcademyRoute
  '/_authenticated/app/admin/ai-audit': typeof AuthenticatedAppAdminAiAuditRoute
  '/_authenticated/app/admin/analytics': typeof AuthenticatedAppAdminAnalyticsRoute
  '/_authenticated/app/admin/audit': typeof AuthenticatedAppAdminAuditRoute
  '/_authenticated/app/admin/companies': typeof AuthenticatedAppAdminCompaniesRoute
  '/_authenticated/app/admin/customers': typeof AuthenticatedAppAdminCustomersRoute
  '/_authenticated/app/admin/dashboard': typeof AuthenticatedAppAdminDashboardRoute
  '/_authenticated/app/admin/knowledge-gaps': typeof AuthenticatedAppAdminKnowledgeGapsRoute
  '/_authenticated/app/admin/platform': typeof AuthenticatedAppAdminPlatformRoute
  '/_authenticated/app/admin/platform-admins': typeof AuthenticatedAppAdminPlatformAdminsRoute
  '/_authenticated/app/admin/sop-generator': typeof AuthenticatedAppAdminSopGeneratorRoute
  '/_authenticated/app/admin/support': typeof AuthenticatedAppAdminSupportRoute
  '/_authenticated/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/_authenticated/app/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/_authenticated/app/internal/assistant': typeof AuthenticatedAppInternalAssistantRoute
  '/_authenticated/app/internal/knowledge': typeof AuthenticatedAppInternalKnowledgeRouteWithChildren
  '/_authenticated/app/workspace/$sessionId': typeof AuthenticatedAppWorkspaceSessionIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/app/academy/': typeof AuthenticatedAppAcademyIndexRoute
  '/_authenticated/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/_authenticated/app/internal/': typeof AuthenticatedAppInternalIndexRoute
  '/_authenticated/app/workspace/': typeof AuthenticatedAppWorkspaceIndexRoute
  '/_authenticated/app/academy/lesson/$lessonId': typeof AuthenticatedAppAcademyLessonLessonIdRoute
  '/_authenticated/app/academy/path/$pathId': typeof AuthenticatedAppAcademyPathPathIdRoute
  '/_authenticated/app/internal/knowledge/$slug': typeof AuthenticatedAppInternalKnowledgeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/accept-invite'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/features'
    | '/forgot-password'
    | '/industries'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/sitemap.xml'
    | '/solutions'
    | '/trust'
    | '/app'
    | '/api/academy-chat'
    | '/api/chat'
    | '/api/customer-writer'
    | '/api/demo-chat'
    | '/api/internal-chat'
    | '/api/workspace-chat'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/responsible-ai'
    | '/legal/terms'
    | '/trust/audit-logs'
    | '/trust/availability'
    | '/trust/backup-policy'
    | '/trust/data-retention'
    | '/trust/encryption'
    | '/trust/gdpr'
    | '/trust/incident-response'
    | '/trust/iso-27001-roadmap'
    | '/trust/multi-tenant-isolation'
    | '/trust/responsible-ai'
    | '/trust/security-architecture'
    | '/verify/$code'
    | '/app/brand'
    | '/app/faq'
    | '/app/internal'
    | '/app/knowledge'
    | '/app/profile'
    | '/app/requests'
    | '/lovable/email/suppression'
    | '/app/'
    | '/app/academy/analytics'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/kb'
    | '/app/academy/settings'
    | '/app/admin/academy'
    | '/app/admin/ai-audit'
    | '/app/admin/analytics'
    | '/app/admin/audit'
    | '/app/admin/companies'
    | '/app/admin/customers'
    | '/app/admin/dashboard'
    | '/app/admin/knowledge-gaps'
    | '/app/admin/platform'
    | '/app/admin/platform-admins'
    | '/app/admin/sop-generator'
    | '/app/admin/support'
    | '/app/admin/users'
    | '/app/chat/$threadId'
    | '/app/internal/assistant'
    | '/app/internal/knowledge'
    | '/app/workspace/$sessionId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/academy/'
    | '/app/chat/'
    | '/app/internal/'
    | '/app/workspace/'
    | '/app/academy/lesson/$lessonId'
    | '/app/academy/path/$pathId'
    | '/app/internal/knowledge/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/accept-invite'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/features'
    | '/forgot-password'
    | '/industries'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/sitemap.xml'
    | '/solutions'
    | '/trust'
    | '/api/academy-chat'
    | '/api/chat'
    | '/api/customer-writer'
    | '/api/demo-chat'
    | '/api/internal-chat'
    | '/api/workspace-chat'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/responsible-ai'
    | '/legal/terms'
    | '/trust/audit-logs'
    | '/trust/availability'
    | '/trust/backup-policy'
    | '/trust/data-retention'
    | '/trust/encryption'
    | '/trust/gdpr'
    | '/trust/incident-response'
    | '/trust/iso-27001-roadmap'
    | '/trust/multi-tenant-isolation'
    | '/trust/responsible-ai'
    | '/trust/security-architecture'
    | '/verify/$code'
    | '/app/brand'
    | '/app/faq'
    | '/app/knowledge'
    | '/app/profile'
    | '/app/requests'
    | '/lovable/email/suppression'
    | '/app'
    | '/app/academy/analytics'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/kb'
    | '/app/academy/settings'
    | '/app/admin/academy'
    | '/app/admin/ai-audit'
    | '/app/admin/analytics'
    | '/app/admin/audit'
    | '/app/admin/companies'
    | '/app/admin/customers'
    | '/app/admin/dashboard'
    | '/app/admin/knowledge-gaps'
    | '/app/admin/platform'
    | '/app/admin/platform-admins'
    | '/app/admin/sop-generator'
    | '/app/admin/support'
    | '/app/admin/users'
    | '/app/chat/$threadId'
    | '/app/internal/assistant'
    | '/app/internal/knowledge'
    | '/app/workspace/$sessionId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/academy'
    | '/app/chat'
    | '/app/internal'
    | '/app/workspace'
    | '/app/academy/lesson/$lessonId'
    | '/app/academy/path/$pathId'
    | '/app/internal/knowledge/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/legal'
    | '/accept-invite'
    | '/auth'
    | '/contact'
    | '/demo'
    | '/features'
    | '/forgot-password'
    | '/industries'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/sitemap.xml'
    | '/solutions'
    | '/trust'
    | '/_authenticated/app'
    | '/api/academy-chat'
    | '/api/chat'
    | '/api/customer-writer'
    | '/api/demo-chat'
    | '/api/internal-chat'
    | '/api/workspace-chat'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/responsible-ai'
    | '/legal/terms'
    | '/trust/audit-logs'
    | '/trust/availability'
    | '/trust/backup-policy'
    | '/trust/data-retention'
    | '/trust/encryption'
    | '/trust/gdpr'
    | '/trust/incident-response'
    | '/trust/iso-27001-roadmap'
    | '/trust/multi-tenant-isolation'
    | '/trust/responsible-ai'
    | '/trust/security-architecture'
    | '/verify/$code'
    | '/_authenticated/app/brand'
    | '/_authenticated/app/faq'
    | '/_authenticated/app/internal'
    | '/_authenticated/app/knowledge'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/requests'
    | '/lovable/email/suppression'
    | '/_authenticated/app/'
    | '/_authenticated/app/academy/analytics'
    | '/_authenticated/app/academy/certificates'
    | '/_authenticated/app/academy/courses'
    | '/_authenticated/app/academy/kb'
    | '/_authenticated/app/academy/settings'
    | '/_authenticated/app/admin/academy'
    | '/_authenticated/app/admin/ai-audit'
    | '/_authenticated/app/admin/analytics'
    | '/_authenticated/app/admin/audit'
    | '/_authenticated/app/admin/companies'
    | '/_authenticated/app/admin/customers'
    | '/_authenticated/app/admin/dashboard'
    | '/_authenticated/app/admin/knowledge-gaps'
    | '/_authenticated/app/admin/platform'
    | '/_authenticated/app/admin/platform-admins'
    | '/_authenticated/app/admin/sop-generator'
    | '/_authenticated/app/admin/support'
    | '/_authenticated/app/admin/users'
    | '/_authenticated/app/chat/$threadId'
    | '/_authenticated/app/internal/assistant'
    | '/_authenticated/app/internal/knowledge'
    | '/_authenticated/app/workspace/$sessionId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/app/academy/'
    | '/_authenticated/app/chat/'
    | '/_authenticated/app/internal/'
    | '/_authenticated/app/workspace/'
    | '/_authenticated/app/academy/lesson/$lessonId'
    | '/_authenticated/app/academy/path/$pathId'
    | '/_authenticated/app/internal/knowledge/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  TrustRoute: typeof TrustRouteWithChildren
  ApiAcademyChatRoute: typeof ApiAcademyChatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCustomerWriterRoute: typeof ApiCustomerWriterRoute
  ApiDemoChatRoute: typeof ApiDemoChatRoute
  ApiInternalChatRoute: typeof ApiInternalChatRoute
  ApiWorkspaceChatRoute: typeof ApiWorkspaceChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/security-architecture': {
      id: '/trust/security-architecture'
      path: '/security-architecture'
      fullPath: '/trust/security-architecture'
      preLoaderRoute: typeof TrustSecurityArchitectureRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/responsible-ai': {
      id: '/trust/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/trust/responsible-ai'
      preLoaderRoute: typeof TrustResponsibleAiRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/multi-tenant-isolation': {
      id: '/trust/multi-tenant-isolation'
      path: '/multi-tenant-isolation'
      fullPath: '/trust/multi-tenant-isolation'
      preLoaderRoute: typeof TrustMultiTenantIsolationRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/iso-27001-roadmap': {
      id: '/trust/iso-27001-roadmap'
      path: '/iso-27001-roadmap'
      fullPath: '/trust/iso-27001-roadmap'
      preLoaderRoute: typeof TrustIso27001RoadmapRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/incident-response': {
      id: '/trust/incident-response'
      path: '/incident-response'
      fullPath: '/trust/incident-response'
      preLoaderRoute: typeof TrustIncidentResponseRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/gdpr': {
      id: '/trust/gdpr'
      path: '/gdpr'
      fullPath: '/trust/gdpr'
      preLoaderRoute: typeof TrustGdprRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/encryption': {
      id: '/trust/encryption'
      path: '/encryption'
      fullPath: '/trust/encryption'
      preLoaderRoute: typeof TrustEncryptionRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/data-retention': {
      id: '/trust/data-retention'
      path: '/data-retention'
      fullPath: '/trust/data-retention'
      preLoaderRoute: typeof TrustDataRetentionRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/backup-policy': {
      id: '/trust/backup-policy'
      path: '/backup-policy'
      fullPath: '/trust/backup-policy'
      preLoaderRoute: typeof TrustBackupPolicyRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/availability': {
      id: '/trust/availability'
      path: '/availability'
      fullPath: '/trust/availability'
      preLoaderRoute: typeof TrustAvailabilityRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/audit-logs': {
      id: '/trust/audit-logs'
      path: '/audit-logs'
      fullPath: '/trust/audit-logs'
      preLoaderRoute: typeof TrustAuditLogsRouteImport
      parentRoute: typeof TrustRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/responsible-ai': {
      id: '/legal/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/legal/responsible-ai'
      preLoaderRoute: typeof LegalResponsibleAiRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace-chat': {
      id: '/api/workspace-chat'
      path: '/api/workspace-chat'
      fullPath: '/api/workspace-chat'
      preLoaderRoute: typeof ApiWorkspaceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat': {
      id: '/api/internal-chat'
      path: '/api/internal-chat'
      fullPath: '/api/internal-chat'
      preLoaderRoute: typeof ApiInternalChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-chat': {
      id: '/api/demo-chat'
      path: '/api/demo-chat'
      fullPath: '/api/demo-chat'
      preLoaderRoute: typeof ApiDemoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-writer': {
      id: '/api/customer-writer'
      path: '/api/customer-writer'
      fullPath: '/api/customer-writer'
      preLoaderRoute: typeof ApiCustomerWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academy-chat': {
      id: '/api/academy-chat'
      path: '/api/academy-chat'
      fullPath: '/api/academy-chat'
      preLoaderRoute: typeof ApiAcademyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/requests': {
      id: '/_authenticated/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AuthenticatedAppRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/knowledge': {
      id: '/_authenticated/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AuthenticatedAppKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/internal': {
      id: '/_authenticated/app/internal'
      path: '/internal'
      fullPath: '/app/internal'
      preLoaderRoute: typeof AuthenticatedAppInternalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/faq': {
      id: '/_authenticated/app/faq'
      path: '/faq'
      fullPath: '/app/faq'
      preLoaderRoute: typeof AuthenticatedAppFaqRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brand': {
      id: '/_authenticated/app/brand'
      path: '/brand'
      fullPath: '/app/brand'
      preLoaderRoute: typeof AuthenticatedAppBrandRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/workspace/': {
      id: '/_authenticated/app/workspace/'
      path: '/workspace'
      fullPath: '/app/workspace/'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/internal/': {
      id: '/_authenticated/app/internal/'
      path: '/'
      fullPath: '/app/internal/'
      preLoaderRoute: typeof AuthenticatedAppInternalIndexRouteImport
      parentRoute: typeof AuthenticatedAppInternalRoute
    }
    '/_authenticated/app/chat/': {
      id: '/_authenticated/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/': {
      id: '/_authenticated/app/academy/'
      path: '/academy'
      fullPath: '/app/academy/'
      preLoaderRoute: typeof AuthenticatedAppAcademyIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/workspace/$sessionId': {
      id: '/_authenticated/app/workspace/$sessionId'
      path: '/workspace/$sessionId'
      fullPath: '/app/workspace/$sessionId'
      preLoaderRoute: typeof AuthenticatedAppWorkspaceSessionIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/internal/knowledge': {
      id: '/_authenticated/app/internal/knowledge'
      path: '/knowledge'
      fullPath: '/app/internal/knowledge'
      preLoaderRoute: typeof AuthenticatedAppInternalKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAppInternalRoute
    }
    '/_authenticated/app/internal/assistant': {
      id: '/_authenticated/app/internal/assistant'
      path: '/assistant'
      fullPath: '/app/internal/assistant'
      preLoaderRoute: typeof AuthenticatedAppInternalAssistantRouteImport
      parentRoute: typeof AuthenticatedAppInternalRoute
    }
    '/_authenticated/app/chat/$threadId': {
      id: '/_authenticated/app/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/app/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedAppChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/users': {
      id: '/_authenticated/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AuthenticatedAppAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/support': {
      id: '/_authenticated/app/admin/support'
      path: '/admin/support'
      fullPath: '/app/admin/support'
      preLoaderRoute: typeof AuthenticatedAppAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/sop-generator': {
      id: '/_authenticated/app/admin/sop-generator'
      path: '/admin/sop-generator'
      fullPath: '/app/admin/sop-generator'
      preLoaderRoute: typeof AuthenticatedAppAdminSopGeneratorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/platform-admins': {
      id: '/_authenticated/app/admin/platform-admins'
      path: '/admin/platform-admins'
      fullPath: '/app/admin/platform-admins'
      preLoaderRoute: typeof AuthenticatedAppAdminPlatformAdminsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/platform': {
      id: '/_authenticated/app/admin/platform'
      path: '/admin/platform'
      fullPath: '/app/admin/platform'
      preLoaderRoute: typeof AuthenticatedAppAdminPlatformRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/knowledge-gaps': {
      id: '/_authenticated/app/admin/knowledge-gaps'
      path: '/admin/knowledge-gaps'
      fullPath: '/app/admin/knowledge-gaps'
      preLoaderRoute: typeof AuthenticatedAppAdminKnowledgeGapsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/dashboard': {
      id: '/_authenticated/app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAppAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/customers': {
      id: '/_authenticated/app/admin/customers'
      path: '/admin/customers'
      fullPath: '/app/admin/customers'
      preLoaderRoute: typeof AuthenticatedAppAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/companies': {
      id: '/_authenticated/app/admin/companies'
      path: '/admin/companies'
      fullPath: '/app/admin/companies'
      preLoaderRoute: typeof AuthenticatedAppAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/audit': {
      id: '/_authenticated/app/admin/audit'
      path: '/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AuthenticatedAppAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/analytics': {
      id: '/_authenticated/app/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/app/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAppAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/ai-audit': {
      id: '/_authenticated/app/admin/ai-audit'
      path: '/admin/ai-audit'
      fullPath: '/app/admin/ai-audit'
      preLoaderRoute: typeof AuthenticatedAppAdminAiAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/academy': {
      id: '/_authenticated/app/admin/academy'
      path: '/admin/academy'
      fullPath: '/app/admin/academy'
      preLoaderRoute: typeof AuthenticatedAppAdminAcademyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/settings': {
      id: '/_authenticated/app/academy/settings'
      path: '/academy/settings'
      fullPath: '/app/academy/settings'
      preLoaderRoute: typeof AuthenticatedAppAcademySettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/kb': {
      id: '/_authenticated/app/academy/kb'
      path: '/academy/kb'
      fullPath: '/app/academy/kb'
      preLoaderRoute: typeof AuthenticatedAppAcademyKbRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/courses': {
      id: '/_authenticated/app/academy/courses'
      path: '/academy/courses'
      fullPath: '/app/academy/courses'
      preLoaderRoute: typeof AuthenticatedAppAcademyCoursesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/certificates': {
      id: '/_authenticated/app/academy/certificates'
      path: '/academy/certificates'
      fullPath: '/app/academy/certificates'
      preLoaderRoute: typeof AuthenticatedAppAcademyCertificatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/analytics': {
      id: '/_authenticated/app/academy/analytics'
      path: '/academy/analytics'
      fullPath: '/app/academy/analytics'
      preLoaderRoute: typeof AuthenticatedAppAcademyAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/internal/knowledge/$slug': {
      id: '/_authenticated/app/internal/knowledge/$slug'
      path: '/$slug'
      fullPath: '/app/internal/knowledge/$slug'
      preLoaderRoute: typeof AuthenticatedAppInternalKnowledgeSlugRouteImport
      parentRoute: typeof AuthenticatedAppInternalKnowledgeRoute
    }
    '/_authenticated/app/academy/path/$pathId': {
      id: '/_authenticated/app/academy/path/$pathId'
      path: '/academy/path/$pathId'
      fullPath: '/app/academy/path/$pathId'
      preLoaderRoute: typeof AuthenticatedAppAcademyPathPathIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/lesson/$lessonId': {
      id: '/_authenticated/app/academy/lesson/$lessonId'
      path: '/academy/lesson/$lessonId'
      fullPath: '/app/academy/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedAppAcademyLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppInternalKnowledgeRouteChildren {
  AuthenticatedAppInternalKnowledgeSlugRoute: typeof AuthenticatedAppInternalKnowledgeSlugRoute
}

const AuthenticatedAppInternalKnowledgeRouteChildren: AuthenticatedAppInternalKnowledgeRouteChildren =
  {
    AuthenticatedAppInternalKnowledgeSlugRoute:
      AuthenticatedAppInternalKnowledgeSlugRoute,
  }

const AuthenticatedAppInternalKnowledgeRouteWithChildren =
  AuthenticatedAppInternalKnowledgeRoute._addFileChildren(
    AuthenticatedAppInternalKnowledgeRouteChildren,
  )

interface AuthenticatedAppInternalRouteChildren {
  AuthenticatedAppInternalAssistantRoute: typeof AuthenticatedAppInternalAssistantRoute
  AuthenticatedAppInternalKnowledgeRoute: typeof AuthenticatedAppInternalKnowledgeRouteWithChildren
  AuthenticatedAppInternalIndexRoute: typeof AuthenticatedAppInternalIndexRoute
}

const AuthenticatedAppInternalRouteChildren: AuthenticatedAppInternalRouteChildren =
  {
    AuthenticatedAppInternalAssistantRoute:
      AuthenticatedAppInternalAssistantRoute,
    AuthenticatedAppInternalKnowledgeRoute:
      AuthenticatedAppInternalKnowledgeRouteWithChildren,
    AuthenticatedAppInternalIndexRoute: AuthenticatedAppInternalIndexRoute,
  }

const AuthenticatedAppInternalRouteWithChildren =
  AuthenticatedAppInternalRoute._addFileChildren(
    AuthenticatedAppInternalRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBrandRoute: typeof AuthenticatedAppBrandRoute
  AuthenticatedAppFaqRoute: typeof AuthenticatedAppFaqRoute
  AuthenticatedAppInternalRoute: typeof AuthenticatedAppInternalRouteWithChildren
  AuthenticatedAppKnowledgeRoute: typeof AuthenticatedAppKnowledgeRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRequestsRoute: typeof AuthenticatedAppRequestsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAcademyAnalyticsRoute: typeof AuthenticatedAppAcademyAnalyticsRoute
  AuthenticatedAppAcademyCertificatesRoute: typeof AuthenticatedAppAcademyCertificatesRoute
  AuthenticatedAppAcademyCoursesRoute: typeof AuthenticatedAppAcademyCoursesRoute
  AuthenticatedAppAcademyKbRoute: typeof AuthenticatedAppAcademyKbRoute
  AuthenticatedAppAcademySettingsRoute: typeof AuthenticatedAppAcademySettingsRoute
  AuthenticatedAppAdminAcademyRoute: typeof AuthenticatedAppAdminAcademyRoute
  AuthenticatedAppAdminAiAuditRoute: typeof AuthenticatedAppAdminAiAuditRoute
  AuthenticatedAppAdminAnalyticsRoute: typeof AuthenticatedAppAdminAnalyticsRoute
  AuthenticatedAppAdminAuditRoute: typeof AuthenticatedAppAdminAuditRoute
  AuthenticatedAppAdminCompaniesRoute: typeof AuthenticatedAppAdminCompaniesRoute
  AuthenticatedAppAdminCustomersRoute: typeof AuthenticatedAppAdminCustomersRoute
  AuthenticatedAppAdminDashboardRoute: typeof AuthenticatedAppAdminDashboardRoute
  AuthenticatedAppAdminKnowledgeGapsRoute: typeof AuthenticatedAppAdminKnowledgeGapsRoute
  AuthenticatedAppAdminPlatformRoute: typeof AuthenticatedAppAdminPlatformRoute
  AuthenticatedAppAdminPlatformAdminsRoute: typeof AuthenticatedAppAdminPlatformAdminsRoute
  AuthenticatedAppAdminSopGeneratorRoute: typeof AuthenticatedAppAdminSopGeneratorRoute
  AuthenticatedAppAdminSupportRoute: typeof AuthenticatedAppAdminSupportRoute
  AuthenticatedAppAdminUsersRoute: typeof AuthenticatedAppAdminUsersRoute
  AuthenticatedAppChatThreadIdRoute: typeof AuthenticatedAppChatThreadIdRoute
  AuthenticatedAppWorkspaceSessionIdRoute: typeof AuthenticatedAppWorkspaceSessionIdRoute
  AuthenticatedAppAcademyIndexRoute: typeof AuthenticatedAppAcademyIndexRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
  AuthenticatedAppWorkspaceIndexRoute: typeof AuthenticatedAppWorkspaceIndexRoute
  AuthenticatedAppAcademyLessonLessonIdRoute: typeof AuthenticatedAppAcademyLessonLessonIdRoute
  AuthenticatedAppAcademyPathPathIdRoute: typeof AuthenticatedAppAcademyPathPathIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBrandRoute: AuthenticatedAppBrandRoute,
  AuthenticatedAppFaqRoute: AuthenticatedAppFaqRoute,
  AuthenticatedAppInternalRoute: AuthenticatedAppInternalRouteWithChildren,
  AuthenticatedAppKnowledgeRoute: AuthenticatedAppKnowledgeRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRequestsRoute: AuthenticatedAppRequestsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAcademyAnalyticsRoute: AuthenticatedAppAcademyAnalyticsRoute,
  AuthenticatedAppAcademyCertificatesRoute:
    AuthenticatedAppAcademyCertificatesRoute,
  AuthenticatedAppAcademyCoursesRoute: AuthenticatedAppAcademyCoursesRoute,
  AuthenticatedAppAcademyKbRoute: AuthenticatedAppAcademyKbRoute,
  AuthenticatedAppAcademySettingsRoute: AuthenticatedAppAcademySettingsRoute,
  AuthenticatedAppAdminAcademyRoute: AuthenticatedAppAdminAcademyRoute,
  AuthenticatedAppAdminAiAuditRoute: AuthenticatedAppAdminAiAuditRoute,
  AuthenticatedAppAdminAnalyticsRoute: AuthenticatedAppAdminAnalyticsRoute,
  AuthenticatedAppAdminAuditRoute: AuthenticatedAppAdminAuditRoute,
  AuthenticatedAppAdminCompaniesRoute: AuthenticatedAppAdminCompaniesRoute,
  AuthenticatedAppAdminCustomersRoute: AuthenticatedAppAdminCustomersRoute,
  AuthenticatedAppAdminDashboardRoute: AuthenticatedAppAdminDashboardRoute,
  AuthenticatedAppAdminKnowledgeGapsRoute:
    AuthenticatedAppAdminKnowledgeGapsRoute,
  AuthenticatedAppAdminPlatformRoute: AuthenticatedAppAdminPlatformRoute,
  AuthenticatedAppAdminPlatformAdminsRoute:
    AuthenticatedAppAdminPlatformAdminsRoute,
  AuthenticatedAppAdminSopGeneratorRoute:
    AuthenticatedAppAdminSopGeneratorRoute,
  AuthenticatedAppAdminSupportRoute: AuthenticatedAppAdminSupportRoute,
  AuthenticatedAppAdminUsersRoute: AuthenticatedAppAdminUsersRoute,
  AuthenticatedAppChatThreadIdRoute: AuthenticatedAppChatThreadIdRoute,
  AuthenticatedAppWorkspaceSessionIdRoute:
    AuthenticatedAppWorkspaceSessionIdRoute,
  AuthenticatedAppAcademyIndexRoute: AuthenticatedAppAcademyIndexRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
  AuthenticatedAppWorkspaceIndexRoute: AuthenticatedAppWorkspaceIndexRoute,
  AuthenticatedAppAcademyLessonLessonIdRoute:
    AuthenticatedAppAcademyLessonLessonIdRoute,
  AuthenticatedAppAcademyPathPathIdRoute:
    AuthenticatedAppAcademyPathPathIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LegalRouteRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDpaRoute: typeof LegalDpaRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalResponsibleAiRoute: typeof LegalResponsibleAiRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDpaRoute: LegalDpaRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalResponsibleAiRoute: LegalResponsibleAiRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

interface TrustRouteChildren {
  TrustAuditLogsRoute: typeof TrustAuditLogsRoute
  TrustAvailabilityRoute: typeof TrustAvailabilityRoute
  TrustBackupPolicyRoute: typeof TrustBackupPolicyRoute
  TrustDataRetentionRoute: typeof TrustDataRetentionRoute
  TrustEncryptionRoute: typeof TrustEncryptionRoute
  TrustGdprRoute: typeof TrustGdprRoute
  TrustIncidentResponseRoute: typeof TrustIncidentResponseRoute
  TrustIso27001RoadmapRoute: typeof TrustIso27001RoadmapRoute
  TrustMultiTenantIsolationRoute: typeof TrustMultiTenantIsolationRoute
  TrustResponsibleAiRoute: typeof TrustResponsibleAiRoute
  TrustSecurityArchitectureRoute: typeof TrustSecurityArchitectureRoute
}

const TrustRouteChildren: TrustRouteChildren = {
  TrustAuditLogsRoute: TrustAuditLogsRoute,
  TrustAvailabilityRoute: TrustAvailabilityRoute,
  TrustBackupPolicyRoute: TrustBackupPolicyRoute,
  TrustDataRetentionRoute: TrustDataRetentionRoute,
  TrustEncryptionRoute: TrustEncryptionRoute,
  TrustGdprRoute: TrustGdprRoute,
  TrustIncidentResponseRoute: TrustIncidentResponseRoute,
  TrustIso27001RoadmapRoute: TrustIso27001RoadmapRoute,
  TrustMultiTenantIsolationRoute: TrustMultiTenantIsolationRoute,
  TrustResponsibleAiRoute: TrustResponsibleAiRoute,
  TrustSecurityArchitectureRoute: TrustSecurityArchitectureRoute,
}

const TrustRouteWithChildren = TrustRoute._addFileChildren(TrustRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  TrustRoute: TrustRouteWithChildren,
  ApiAcademyChatRoute: ApiAcademyChatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCustomerWriterRoute: ApiCustomerWriterRoute,
  ApiDemoChatRoute: ApiDemoChatRoute,
  ApiInternalChatRoute: ApiInternalChatRoute,
  ApiWorkspaceChatRoute: ApiWorkspaceChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
