/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowsOnlyRouteImport } from './routes/windows-only'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SsoSigninRouteImport } from './routes/sso-signin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelfHostedRouteImport } from './routes/self-hosted'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FirstRunRouteImport } from './routes/first-run'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as LegalRouteRouteImport } from './routes/legal/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalResponsibleAiRouteImport } from './routes/legal/responsible-ai'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalImpressumRouteImport } from './routes/legal/impressum'
import { Route as LegalDpaRouteImport } from './routes/legal/dpa'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiWorkspaceChatRouteImport } from './routes/api/workspace-chat'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiInternalChatRouteImport } from './routes/api/internal-chat'
import { Route as ApiCustomerWriterRouteImport } from './routes/api/customer-writer'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAcademyChatRouteImport } from './routes/api/academy-chat'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedManagementRouteImport } from './routes/_authenticated/management'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedManagementIndexRouteImport } from './routes/_authenticated/management.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api.public.contact-submit'
import { Route as AuthenticatedPortalSupportRouteImport } from './routes/_authenticated/portal.support'
import { Route as AuthenticatedPortalSubscriptionRouteImport } from './routes/_authenticated/portal.subscription'
import { Route as AuthenticatedPortalReleaseNotesRouteImport } from './routes/_authenticated/portal.release-notes'
import { Route as AuthenticatedPortalDownloadsRouteImport } from './routes/_authenticated/portal.downloads'
import { Route as AuthenticatedPortalDocumentationRouteImport } from './routes/_authenticated/portal.documentation'
import { Route as AuthenticatedPortalAdminRouteImport } from './routes/_authenticated/portal.admin'
import { Route as AuthenticatedManagementSupportRouteImport } from './routes/_authenticated/management.support'
import { Route as AuthenticatedManagementSettingsRouteImport } from './routes/_authenticated/management.settings'
import { Route as AuthenticatedManagementReleasesRouteImport } from './routes/_authenticated/management.releases'
import { Route as AuthenticatedManagementPortalRouteImport } from './routes/_authenticated/management.portal'
import { Route as AuthenticatedManagementOwnershipRouteImport } from './routes/_authenticated/management.ownership'
import { Route as AuthenticatedManagementLicensesRouteImport } from './routes/_authenticated/management.licenses'
import { Route as AuthenticatedManagementInstallationsRouteImport } from './routes/_authenticated/management.installations'
import { Route as AuthenticatedManagementCustomersRouteImport } from './routes/_authenticated/management.customers'
import { Route as AuthenticatedManagementCompaniesRouteImport } from './routes/_authenticated/management.companies'
import { Route as AuthenticatedManagementAuditLogsRouteImport } from './routes/_authenticated/management.audit-logs'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app.users'
import { Route as AuthenticatedAppUpdatesRouteImport } from './routes/_authenticated/app.updates'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/app.subscription'
import { Route as AuthenticatedAppOrganizationRouteImport } from './routes/_authenticated/app.organization'
import { Route as AuthenticatedAppModulesRouteImport } from './routes/_authenticated/app.modules'
import { Route as AuthenticatedAppKnowledgeRouteImport } from './routes/_authenticated/app.knowledge'
import { Route as AuthenticatedAppFaqRouteImport } from './routes/_authenticated/app.faq'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedPortalAdminIndexRouteImport } from './routes/_authenticated/portal.admin.index'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/app.chat.index'
import { Route as AuthenticatedAppAcademyIndexRouteImport } from './routes/_authenticated/app.academy.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicV1KnowledgeRouteImport } from './routes/api/public/v1/knowledge'
import { Route as ApiPublicV1FaqsRouteImport } from './routes/api/public/v1/faqs'
import { Route as AuthenticatedPortalAdminDownloadsRouteImport } from './routes/_authenticated/portal.admin.downloads'
import { Route as AuthenticatedManagementCompaniesIdRouteImport } from './routes/_authenticated/management.companies.$id'
import { Route as AuthenticatedAppChatThreadIdRouteImport } from './routes/_authenticated/app.chat.$threadId'
import { Route as AuthenticatedAppAcademyTeacherRouteImport } from './routes/_authenticated/app.academy.teacher'
import { Route as AuthenticatedAppAcademySettingsRouteImport } from './routes/_authenticated/app.academy.settings'
import { Route as AuthenticatedAppAcademyKbRouteImport } from './routes/_authenticated/app.academy.kb'
import { Route as AuthenticatedAppAcademyCoursesRouteImport } from './routes/_authenticated/app.academy.courses'
import { Route as AuthenticatedAppAcademyCertificatesRouteImport } from './routes/_authenticated/app.academy.certificates'
import { Route as AuthenticatedAppAcademyAnalyticsRouteImport } from './routes/_authenticated/app.academy.analytics'
import { Route as ApiPublicV1LicenseReleasesRouteImport } from './routes/api/public/v1/license/releases'
import { Route as ApiPublicV1LicenseHeartbeatRouteImport } from './routes/api/public/v1/license/heartbeat'
import { Route as AuthenticatedAppAcademyPathPathIdRouteImport } from './routes/_authenticated/app.academy.path.$pathId'
import { Route as AuthenticatedAppAcademyLessonLessonIdRouteImport } from './routes/_authenticated/app.academy.lesson.$lessonId'

const WindowsOnlyRoute = WindowsOnlyRouteImport.update({
  id: '/windows-only',
  path: '/windows-only',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoSigninRoute = SsoSigninRouteImport.update({
  id: '/sso-signin',
  path: '/sso-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostedRoute = SelfHostedRouteImport.update({
  id: '/self-hosted',
  path: '/self-hosted',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstRunRoute = FirstRunRouteImport.update({
  id: '/first-run',
  path: '/first-run',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalResponsibleAiRoute = LegalResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRouteRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceChatRoute = ApiWorkspaceChatRouteImport.update({
  id: '/api/workspace-chat',
  path: '/api/workspace-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatRoute = ApiInternalChatRouteImport.update({
  id: '/api/internal-chat',
  path: '/api/internal-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerWriterRoute = ApiCustomerWriterRouteImport.update({
  id: '/api/customer-writer',
  path: '/api/customer-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademyChatRoute = ApiAcademyChatRouteImport.update({
  id: '/api/academy-chat',
  path: '/api/academy-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagementRoute = AuthenticatedManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedManagementIndexRoute =
  AuthenticatedManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact-submit',
  path: '/api/public/contact-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalSupportRoute =
  AuthenticatedPortalSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSubscriptionRoute =
  AuthenticatedPortalSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalReleaseNotesRoute =
  AuthenticatedPortalReleaseNotesRouteImport.update({
    id: '/release-notes',
    path: '/release-notes',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDownloadsRoute =
  AuthenticatedPortalDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentationRoute =
  AuthenticatedPortalDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAdminRoute =
  AuthenticatedPortalAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedManagementSupportRoute =
  AuthenticatedManagementSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementSettingsRoute =
  AuthenticatedManagementSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementReleasesRoute =
  AuthenticatedManagementReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementPortalRoute =
  AuthenticatedManagementPortalRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementOwnershipRoute =
  AuthenticatedManagementOwnershipRouteImport.update({
    id: '/ownership',
    path: '/ownership',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementLicensesRoute =
  AuthenticatedManagementLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementInstallationsRoute =
  AuthenticatedManagementInstallationsRouteImport.update({
    id: '/installations',
    path: '/installations',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementCustomersRoute =
  AuthenticatedManagementCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementCompaniesRoute =
  AuthenticatedManagementCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedManagementAuditLogsRoute =
  AuthenticatedManagementAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedManagementRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUpdatesRoute = AuthenticatedAppUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOrganizationRoute =
  AuthenticatedAppOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModulesRoute = AuthenticatedAppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppKnowledgeRoute =
  AuthenticatedAppKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFaqRoute = AuthenticatedAppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalAdminIndexRoute =
  AuthenticatedPortalAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalAdminRoute,
  } as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppAcademyIndexRoute =
  AuthenticatedAppAcademyIndexRouteImport.update({
    id: '/academy/',
    path: '/academy/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1KnowledgeRoute = ApiPublicV1KnowledgeRouteImport.update({
  id: '/api/public/v1/knowledge',
  path: '/api/public/v1/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FaqsRoute = ApiPublicV1FaqsRouteImport.update({
  id: '/api/public/v1/faqs',
  path: '/api/public/v1/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalAdminDownloadsRoute =
  AuthenticatedPortalAdminDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedPortalAdminRoute,
  } as any)
const AuthenticatedManagementCompaniesIdRoute =
  AuthenticatedManagementCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedManagementCompaniesRoute,
  } as any)
const AuthenticatedAppChatThreadIdRoute =
  AuthenticatedAppChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppAcademyTeacherRoute =
  AuthenticatedAppAcademyTeacherRouteImport.update({
    id: '/academy/teacher',
    path: '/academy/teacher',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademySettingsRoute =
  AuthenticatedAppAcademySettingsRouteImport.update({
    id: '/academy/settings',
    path: '/academy/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyKbRoute =
  AuthenticatedAppAcademyKbRouteImport.update({
    id: '/academy/kb',
    path: '/academy/kb',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyCoursesRoute =
  AuthenticatedAppAcademyCoursesRouteImport.update({
    id: '/academy/courses',
    path: '/academy/courses',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyCertificatesRoute =
  AuthenticatedAppAcademyCertificatesRouteImport.update({
    id: '/academy/certificates',
    path: '/academy/certificates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyAnalyticsRoute =
  AuthenticatedAppAcademyAnalyticsRouteImport.update({
    id: '/academy/analytics',
    path: '/academy/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicV1LicenseReleasesRoute =
  ApiPublicV1LicenseReleasesRouteImport.update({
    id: '/api/public/v1/license/releases',
    path: '/api/public/v1/license/releases',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1LicenseHeartbeatRoute =
  ApiPublicV1LicenseHeartbeatRouteImport.update({
    id: '/api/public/v1/license/heartbeat',
    path: '/api/public/v1/license/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAcademyPathPathIdRoute =
  AuthenticatedAppAcademyPathPathIdRouteImport.update({
    id: '/academy/path/$pathId',
    path: '/academy/path/$pathId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAcademyLessonLessonIdRoute =
  AuthenticatedAppAcademyLessonLessonIdRouteImport.update({
    id: '/academy/lesson/$lessonId',
    path: '/academy/lesson/$lessonId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/first-run': typeof FirstRunRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/self-hosted': typeof SelfHostedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso-signin': typeof SsoSigninRoute
  '/support': typeof SupportRoute
  '/windows-only': typeof WindowsOnlyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/management': typeof AuthenticatedManagementRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/api/academy-chat': typeof ApiAcademyChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/customer-writer': typeof ApiCustomerWriterRoute
  '/api/internal-chat': typeof ApiInternalChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workspace-chat': typeof ApiWorkspaceChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/responsible-ai': typeof LegalResponsibleAiRoute
  '/legal/terms': typeof LegalTermsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/app/faq': typeof AuthenticatedAppFaqRoute
  '/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/app/modules': typeof AuthenticatedAppModulesRoute
  '/app/organization': typeof AuthenticatedAppOrganizationRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/app/updates': typeof AuthenticatedAppUpdatesRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/management/audit-logs': typeof AuthenticatedManagementAuditLogsRoute
  '/management/companies': typeof AuthenticatedManagementCompaniesRouteWithChildren
  '/management/customers': typeof AuthenticatedManagementCustomersRoute
  '/management/installations': typeof AuthenticatedManagementInstallationsRoute
  '/management/licenses': typeof AuthenticatedManagementLicensesRoute
  '/management/ownership': typeof AuthenticatedManagementOwnershipRoute
  '/management/portal': typeof AuthenticatedManagementPortalRoute
  '/management/releases': typeof AuthenticatedManagementReleasesRoute
  '/management/settings': typeof AuthenticatedManagementSettingsRoute
  '/management/support': typeof AuthenticatedManagementSupportRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRouteWithChildren
  '/portal/documentation': typeof AuthenticatedPortalDocumentationRoute
  '/portal/downloads': typeof AuthenticatedPortalDownloadsRoute
  '/portal/release-notes': typeof AuthenticatedPortalReleaseNotesRoute
  '/portal/subscription': typeof AuthenticatedPortalSubscriptionRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/management/': typeof AuthenticatedManagementIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/app/academy/analytics': typeof AuthenticatedAppAcademyAnalyticsRoute
  '/app/academy/certificates': typeof AuthenticatedAppAcademyCertificatesRoute
  '/app/academy/courses': typeof AuthenticatedAppAcademyCoursesRoute
  '/app/academy/kb': typeof AuthenticatedAppAcademyKbRoute
  '/app/academy/settings': typeof AuthenticatedAppAcademySettingsRoute
  '/app/academy/teacher': typeof AuthenticatedAppAcademyTeacherRoute
  '/app/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/management/companies/$id': typeof AuthenticatedManagementCompaniesIdRoute
  '/portal/admin/downloads': typeof AuthenticatedPortalAdminDownloadsRoute
  '/api/public/v1/faqs': typeof ApiPublicV1FaqsRoute
  '/api/public/v1/knowledge': typeof ApiPublicV1KnowledgeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/academy/': typeof AuthenticatedAppAcademyIndexRoute
  '/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/portal/admin/': typeof AuthenticatedPortalAdminIndexRoute
  '/app/academy/lesson/$lessonId': typeof AuthenticatedAppAcademyLessonLessonIdRoute
  '/app/academy/path/$pathId': typeof AuthenticatedAppAcademyPathPathIdRoute
  '/api/public/v1/license/heartbeat': typeof ApiPublicV1LicenseHeartbeatRoute
  '/api/public/v1/license/releases': typeof ApiPublicV1LicenseReleasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/first-run': typeof FirstRunRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/self-hosted': typeof SelfHostedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso-signin': typeof SsoSigninRoute
  '/support': typeof SupportRoute
  '/windows-only': typeof WindowsOnlyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/academy-chat': typeof ApiAcademyChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/customer-writer': typeof ApiCustomerWriterRoute
  '/api/internal-chat': typeof ApiInternalChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workspace-chat': typeof ApiWorkspaceChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/responsible-ai': typeof LegalResponsibleAiRoute
  '/legal/terms': typeof LegalTermsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/faq': typeof AuthenticatedAppFaqRoute
  '/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/app/modules': typeof AuthenticatedAppModulesRoute
  '/app/organization': typeof AuthenticatedAppOrganizationRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/app/updates': typeof AuthenticatedAppUpdatesRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/management/audit-logs': typeof AuthenticatedManagementAuditLogsRoute
  '/management/companies': typeof AuthenticatedManagementCompaniesRouteWithChildren
  '/management/customers': typeof AuthenticatedManagementCustomersRoute
  '/management/installations': typeof AuthenticatedManagementInstallationsRoute
  '/management/licenses': typeof AuthenticatedManagementLicensesRoute
  '/management/ownership': typeof AuthenticatedManagementOwnershipRoute
  '/management/portal': typeof AuthenticatedManagementPortalRoute
  '/management/releases': typeof AuthenticatedManagementReleasesRoute
  '/management/settings': typeof AuthenticatedManagementSettingsRoute
  '/management/support': typeof AuthenticatedManagementSupportRoute
  '/portal/documentation': typeof AuthenticatedPortalDocumentationRoute
  '/portal/downloads': typeof AuthenticatedPortalDownloadsRoute
  '/portal/release-notes': typeof AuthenticatedPortalReleaseNotesRoute
  '/portal/subscription': typeof AuthenticatedPortalSubscriptionRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/management': typeof AuthenticatedManagementIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/app/academy/analytics': typeof AuthenticatedAppAcademyAnalyticsRoute
  '/app/academy/certificates': typeof AuthenticatedAppAcademyCertificatesRoute
  '/app/academy/courses': typeof AuthenticatedAppAcademyCoursesRoute
  '/app/academy/kb': typeof AuthenticatedAppAcademyKbRoute
  '/app/academy/settings': typeof AuthenticatedAppAcademySettingsRoute
  '/app/academy/teacher': typeof AuthenticatedAppAcademyTeacherRoute
  '/app/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/management/companies/$id': typeof AuthenticatedManagementCompaniesIdRoute
  '/portal/admin/downloads': typeof AuthenticatedPortalAdminDownloadsRoute
  '/api/public/v1/faqs': typeof ApiPublicV1FaqsRoute
  '/api/public/v1/knowledge': typeof ApiPublicV1KnowledgeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/academy': typeof AuthenticatedAppAcademyIndexRoute
  '/app/chat': typeof AuthenticatedAppChatIndexRoute
  '/portal/admin': typeof AuthenticatedPortalAdminIndexRoute
  '/app/academy/lesson/$lessonId': typeof AuthenticatedAppAcademyLessonLessonIdRoute
  '/app/academy/path/$pathId': typeof AuthenticatedAppAcademyPathPathIdRoute
  '/api/public/v1/license/heartbeat': typeof ApiPublicV1LicenseHeartbeatRoute
  '/api/public/v1/license/releases': typeof ApiPublicV1LicenseReleasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/legal': typeof LegalRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/first-run': typeof FirstRunRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mcp': typeof McpRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/self-hosted': typeof SelfHostedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sso-signin': typeof SsoSigninRoute
  '/support': typeof SupportRoute
  '/windows-only': typeof WindowsOnlyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/management': typeof AuthenticatedManagementRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/api/academy-chat': typeof ApiAcademyChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/customer-writer': typeof ApiCustomerWriterRoute
  '/api/internal-chat': typeof ApiInternalChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workspace-chat': typeof ApiWorkspaceChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/responsible-ai': typeof LegalResponsibleAiRoute
  '/legal/terms': typeof LegalTermsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/app/faq': typeof AuthenticatedAppFaqRoute
  '/_authenticated/app/knowledge': typeof AuthenticatedAppKnowledgeRoute
  '/_authenticated/app/modules': typeof AuthenticatedAppModulesRoute
  '/_authenticated/app/organization': typeof AuthenticatedAppOrganizationRoute
  '/_authenticated/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/_authenticated/app/updates': typeof AuthenticatedAppUpdatesRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/management/audit-logs': typeof AuthenticatedManagementAuditLogsRoute
  '/_authenticated/management/companies': typeof AuthenticatedManagementCompaniesRouteWithChildren
  '/_authenticated/management/customers': typeof AuthenticatedManagementCustomersRoute
  '/_authenticated/management/installations': typeof AuthenticatedManagementInstallationsRoute
  '/_authenticated/management/licenses': typeof AuthenticatedManagementLicensesRoute
  '/_authenticated/management/ownership': typeof AuthenticatedManagementOwnershipRoute
  '/_authenticated/management/portal': typeof AuthenticatedManagementPortalRoute
  '/_authenticated/management/releases': typeof AuthenticatedManagementReleasesRoute
  '/_authenticated/management/settings': typeof AuthenticatedManagementSettingsRoute
  '/_authenticated/management/support': typeof AuthenticatedManagementSupportRoute
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRouteWithChildren
  '/_authenticated/portal/documentation': typeof AuthenticatedPortalDocumentationRoute
  '/_authenticated/portal/downloads': typeof AuthenticatedPortalDownloadsRoute
  '/_authenticated/portal/release-notes': typeof AuthenticatedPortalReleaseNotesRoute
  '/_authenticated/portal/subscription': typeof AuthenticatedPortalSubscriptionRoute
  '/_authenticated/portal/support': typeof AuthenticatedPortalSupportRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/management/': typeof AuthenticatedManagementIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/app/academy/analytics': typeof AuthenticatedAppAcademyAnalyticsRoute
  '/_authenticated/app/academy/certificates': typeof AuthenticatedAppAcademyCertificatesRoute
  '/_authenticated/app/academy/courses': typeof AuthenticatedAppAcademyCoursesRoute
  '/_authenticated/app/academy/kb': typeof AuthenticatedAppAcademyKbRoute
  '/_authenticated/app/academy/settings': typeof AuthenticatedAppAcademySettingsRoute
  '/_authenticated/app/academy/teacher': typeof AuthenticatedAppAcademyTeacherRoute
  '/_authenticated/app/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/_authenticated/management/companies/$id': typeof AuthenticatedManagementCompaniesIdRoute
  '/_authenticated/portal/admin/downloads': typeof AuthenticatedPortalAdminDownloadsRoute
  '/api/public/v1/faqs': typeof ApiPublicV1FaqsRoute
  '/api/public/v1/knowledge': typeof ApiPublicV1KnowledgeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/app/academy/': typeof AuthenticatedAppAcademyIndexRoute
  '/_authenticated/app/chat/': typeof AuthenticatedAppChatIndexRoute
  '/_authenticated/portal/admin/': typeof AuthenticatedPortalAdminIndexRoute
  '/_authenticated/app/academy/lesson/$lessonId': typeof AuthenticatedAppAcademyLessonLessonIdRoute
  '/_authenticated/app/academy/path/$pathId': typeof AuthenticatedAppAcademyPathPathIdRoute
  '/api/public/v1/license/heartbeat': typeof ApiPublicV1LicenseHeartbeatRoute
  '/api/public/v1/license/releases': typeof ApiPublicV1LicenseReleasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/accept-invite'
    | '/auth'
    | '/company'
    | '/contact'
    | '/documentation'
    | '/first-run'
    | '/forgot-password'
    | '/mcp'
    | '/modules'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/self-hosted'
    | '/sitemap.xml'
    | '/sso-signin'
    | '/support'
    | '/windows-only'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/management'
    | '/portal'
    | '/api/academy-chat'
    | '/api/chat'
    | '/api/customer-writer'
    | '/api/internal-chat'
    | '/api/tts'
    | '/api/workspace-chat'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/responsible-ai'
    | '/legal/terms'
    | '/verify/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/audit'
    | '/app/chat'
    | '/app/faq'
    | '/app/knowledge'
    | '/app/modules'
    | '/app/organization'
    | '/app/subscription'
    | '/app/updates'
    | '/app/users'
    | '/management/audit-logs'
    | '/management/companies'
    | '/management/customers'
    | '/management/installations'
    | '/management/licenses'
    | '/management/ownership'
    | '/management/portal'
    | '/management/releases'
    | '/management/settings'
    | '/management/support'
    | '/portal/admin'
    | '/portal/documentation'
    | '/portal/downloads'
    | '/portal/release-notes'
    | '/portal/subscription'
    | '/portal/support'
    | '/api/public/contact-submit'
    | '/lovable/email/suppression'
    | '/app/'
    | '/management/'
    | '/portal/'
    | '/app/academy/analytics'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/kb'
    | '/app/academy/settings'
    | '/app/academy/teacher'
    | '/app/chat/$threadId'
    | '/management/companies/$id'
    | '/portal/admin/downloads'
    | '/api/public/v1/faqs'
    | '/api/public/v1/knowledge'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/academy/'
    | '/app/chat/'
    | '/portal/admin/'
    | '/app/academy/lesson/$lessonId'
    | '/app/academy/path/$pathId'
    | '/api/public/v1/license/heartbeat'
    | '/api/public/v1/license/releases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/accept-invite'
    | '/auth'
    | '/company'
    | '/contact'
    | '/documentation'
    | '/first-run'
    | '/forgot-password'
    | '/mcp'
    | '/modules'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/self-hosted'
    | '/sitemap.xml'
    | '/sso-signin'
    | '/support'
    | '/windows-only'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/academy-chat'
    | '/api/chat'
    | '/api/customer-writer'
    | '/api/internal-chat'
    | '/api/tts'
    | '/api/workspace-chat'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/responsible-ai'
    | '/legal/terms'
    | '/verify/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/audit'
    | '/app/faq'
    | '/app/knowledge'
    | '/app/modules'
    | '/app/organization'
    | '/app/subscription'
    | '/app/updates'
    | '/app/users'
    | '/management/audit-logs'
    | '/management/companies'
    | '/management/customers'
    | '/management/installations'
    | '/management/licenses'
    | '/management/ownership'
    | '/management/portal'
    | '/management/releases'
    | '/management/settings'
    | '/management/support'
    | '/portal/documentation'
    | '/portal/downloads'
    | '/portal/release-notes'
    | '/portal/subscription'
    | '/portal/support'
    | '/api/public/contact-submit'
    | '/lovable/email/suppression'
    | '/app'
    | '/management'
    | '/portal'
    | '/app/academy/analytics'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/kb'
    | '/app/academy/settings'
    | '/app/academy/teacher'
    | '/app/chat/$threadId'
    | '/management/companies/$id'
    | '/portal/admin/downloads'
    | '/api/public/v1/faqs'
    | '/api/public/v1/knowledge'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/academy'
    | '/app/chat'
    | '/portal/admin'
    | '/app/academy/lesson/$lessonId'
    | '/app/academy/path/$pathId'
    | '/api/public/v1/license/heartbeat'
    | '/api/public/v1/license/releases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/legal'
    | '/accept-invite'
    | '/auth'
    | '/company'
    | '/contact'
    | '/documentation'
    | '/first-run'
    | '/forgot-password'
    | '/mcp'
    | '/modules'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/security'
    | '/self-hosted'
    | '/sitemap.xml'
    | '/sso-signin'
    | '/support'
    | '/windows-only'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/_authenticated/management'
    | '/_authenticated/portal'
    | '/api/academy-chat'
    | '/api/chat'
    | '/api/customer-writer'
    | '/api/internal-chat'
    | '/api/tts'
    | '/api/workspace-chat'
    | '/email/unsubscribe'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/responsible-ai'
    | '/legal/terms'
    | '/verify/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/faq'
    | '/_authenticated/app/knowledge'
    | '/_authenticated/app/modules'
    | '/_authenticated/app/organization'
    | '/_authenticated/app/subscription'
    | '/_authenticated/app/updates'
    | '/_authenticated/app/users'
    | '/_authenticated/management/audit-logs'
    | '/_authenticated/management/companies'
    | '/_authenticated/management/customers'
    | '/_authenticated/management/installations'
    | '/_authenticated/management/licenses'
    | '/_authenticated/management/ownership'
    | '/_authenticated/management/portal'
    | '/_authenticated/management/releases'
    | '/_authenticated/management/settings'
    | '/_authenticated/management/support'
    | '/_authenticated/portal/admin'
    | '/_authenticated/portal/documentation'
    | '/_authenticated/portal/downloads'
    | '/_authenticated/portal/release-notes'
    | '/_authenticated/portal/subscription'
    | '/_authenticated/portal/support'
    | '/api/public/contact-submit'
    | '/lovable/email/suppression'
    | '/_authenticated/app/'
    | '/_authenticated/management/'
    | '/_authenticated/portal/'
    | '/_authenticated/app/academy/analytics'
    | '/_authenticated/app/academy/certificates'
    | '/_authenticated/app/academy/courses'
    | '/_authenticated/app/academy/kb'
    | '/_authenticated/app/academy/settings'
    | '/_authenticated/app/academy/teacher'
    | '/_authenticated/app/chat/$threadId'
    | '/_authenticated/management/companies/$id'
    | '/_authenticated/portal/admin/downloads'
    | '/api/public/v1/faqs'
    | '/api/public/v1/knowledge'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/app/academy/'
    | '/_authenticated/app/chat/'
    | '/_authenticated/portal/admin/'
    | '/_authenticated/app/academy/lesson/$lessonId'
    | '/_authenticated/app/academy/path/$pathId'
    | '/api/public/v1/license/heartbeat'
    | '/api/public/v1/license/releases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  DocumentationRoute: typeof DocumentationRoute
  FirstRunRoute: typeof FirstRunRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  McpRoute: typeof McpRoute
  ModulesRoute: typeof ModulesRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SelfHostedRoute: typeof SelfHostedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SsoSigninRoute: typeof SsoSigninRoute
  SupportRoute: typeof SupportRoute
  WindowsOnlyRoute: typeof WindowsOnlyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAcademyChatRoute: typeof ApiAcademyChatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCustomerWriterRoute: typeof ApiCustomerWriterRoute
  ApiInternalChatRoute: typeof ApiInternalChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiWorkspaceChatRoute: typeof ApiWorkspaceChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicV1FaqsRoute: typeof ApiPublicV1FaqsRoute
  ApiPublicV1KnowledgeRoute: typeof ApiPublicV1KnowledgeRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicV1LicenseHeartbeatRoute: typeof ApiPublicV1LicenseHeartbeatRoute
  ApiPublicV1LicenseReleasesRoute: typeof ApiPublicV1LicenseReleasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/windows-only': {
      id: '/windows-only'
      path: '/windows-only'
      fullPath: '/windows-only'
      preLoaderRoute: typeof WindowsOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-signin': {
      id: '/sso-signin'
      path: '/sso-signin'
      fullPath: '/sso-signin'
      preLoaderRoute: typeof SsoSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosted': {
      id: '/self-hosted'
      path: '/self-hosted'
      fullPath: '/self-hosted'
      preLoaderRoute: typeof SelfHostedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-run': {
      id: '/first-run'
      path: '/first-run'
      fullPath: '/first-run'
      preLoaderRoute: typeof FirstRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/responsible-ai': {
      id: '/legal/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/legal/responsible-ai'
      preLoaderRoute: typeof LegalResponsibleAiRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace-chat': {
      id: '/api/workspace-chat'
      path: '/api/workspace-chat'
      fullPath: '/api/workspace-chat'
      preLoaderRoute: typeof ApiWorkspaceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat': {
      id: '/api/internal-chat'
      path: '/api/internal-chat'
      fullPath: '/api/internal-chat'
      preLoaderRoute: typeof ApiInternalChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-writer': {
      id: '/api/customer-writer'
      path: '/api/customer-writer'
      fullPath: '/api/customer-writer'
      preLoaderRoute: typeof ApiCustomerWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academy-chat': {
      id: '/api/academy-chat'
      path: '/api/academy-chat'
      fullPath: '/api/academy-chat'
      preLoaderRoute: typeof ApiAcademyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management': {
      id: '/_authenticated/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AuthenticatedManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/management/': {
      id: '/_authenticated/management/'
      path: '/'
      fullPath: '/management/'
      preLoaderRoute: typeof AuthenticatedManagementIndexRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-submit': {
      id: '/api/public/contact-submit'
      path: '/api/public/contact-submit'
      fullPath: '/api/public/contact-submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/support': {
      id: '/_authenticated/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof AuthenticatedPortalSupportRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/subscription': {
      id: '/_authenticated/portal/subscription'
      path: '/subscription'
      fullPath: '/portal/subscription'
      preLoaderRoute: typeof AuthenticatedPortalSubscriptionRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/release-notes': {
      id: '/_authenticated/portal/release-notes'
      path: '/release-notes'
      fullPath: '/portal/release-notes'
      preLoaderRoute: typeof AuthenticatedPortalReleaseNotesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/downloads': {
      id: '/_authenticated/portal/downloads'
      path: '/downloads'
      fullPath: '/portal/downloads'
      preLoaderRoute: typeof AuthenticatedPortalDownloadsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documentation': {
      id: '/_authenticated/portal/documentation'
      path: '/documentation'
      fullPath: '/portal/documentation'
      preLoaderRoute: typeof AuthenticatedPortalDocumentationRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/management/support': {
      id: '/_authenticated/management/support'
      path: '/support'
      fullPath: '/management/support'
      preLoaderRoute: typeof AuthenticatedManagementSupportRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/settings': {
      id: '/_authenticated/management/settings'
      path: '/settings'
      fullPath: '/management/settings'
      preLoaderRoute: typeof AuthenticatedManagementSettingsRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/releases': {
      id: '/_authenticated/management/releases'
      path: '/releases'
      fullPath: '/management/releases'
      preLoaderRoute: typeof AuthenticatedManagementReleasesRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/portal': {
      id: '/_authenticated/management/portal'
      path: '/portal'
      fullPath: '/management/portal'
      preLoaderRoute: typeof AuthenticatedManagementPortalRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/ownership': {
      id: '/_authenticated/management/ownership'
      path: '/ownership'
      fullPath: '/management/ownership'
      preLoaderRoute: typeof AuthenticatedManagementOwnershipRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/licenses': {
      id: '/_authenticated/management/licenses'
      path: '/licenses'
      fullPath: '/management/licenses'
      preLoaderRoute: typeof AuthenticatedManagementLicensesRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/installations': {
      id: '/_authenticated/management/installations'
      path: '/installations'
      fullPath: '/management/installations'
      preLoaderRoute: typeof AuthenticatedManagementInstallationsRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/customers': {
      id: '/_authenticated/management/customers'
      path: '/customers'
      fullPath: '/management/customers'
      preLoaderRoute: typeof AuthenticatedManagementCustomersRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/companies': {
      id: '/_authenticated/management/companies'
      path: '/companies'
      fullPath: '/management/companies'
      preLoaderRoute: typeof AuthenticatedManagementCompaniesRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/management/audit-logs': {
      id: '/_authenticated/management/audit-logs'
      path: '/audit-logs'
      fullPath: '/management/audit-logs'
      preLoaderRoute: typeof AuthenticatedManagementAuditLogsRouteImport
      parentRoute: typeof AuthenticatedManagementRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/updates': {
      id: '/_authenticated/app/updates'
      path: '/updates'
      fullPath: '/app/updates'
      preLoaderRoute: typeof AuthenticatedAppUpdatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/subscription': {
      id: '/_authenticated/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/organization': {
      id: '/_authenticated/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AuthenticatedAppOrganizationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/modules': {
      id: '/_authenticated/app/modules'
      path: '/modules'
      fullPath: '/app/modules'
      preLoaderRoute: typeof AuthenticatedAppModulesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/knowledge': {
      id: '/_authenticated/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AuthenticatedAppKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/faq': {
      id: '/_authenticated/app/faq'
      path: '/faq'
      fullPath: '/app/faq'
      preLoaderRoute: typeof AuthenticatedAppFaqRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/admin/': {
      id: '/_authenticated/portal/admin/'
      path: '/'
      fullPath: '/portal/admin/'
      preLoaderRoute: typeof AuthenticatedPortalAdminIndexRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRoute
    }
    '/_authenticated/app/chat/': {
      id: '/_authenticated/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/academy/': {
      id: '/_authenticated/app/academy/'
      path: '/academy'
      fullPath: '/app/academy/'
      preLoaderRoute: typeof AuthenticatedAppAcademyIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/knowledge': {
      id: '/api/public/v1/knowledge'
      path: '/api/public/v1/knowledge'
      fullPath: '/api/public/v1/knowledge'
      preLoaderRoute: typeof ApiPublicV1KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/faqs': {
      id: '/api/public/v1/faqs'
      path: '/api/public/v1/faqs'
      fullPath: '/api/public/v1/faqs'
      preLoaderRoute: typeof ApiPublicV1FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/admin/downloads': {
      id: '/_authenticated/portal/admin/downloads'
      path: '/downloads'
      fullPath: '/portal/admin/downloads'
      preLoaderRoute: typeof AuthenticatedPortalAdminDownloadsRouteImport
      parentRoute: typeof AuthenticatedPortalAdminRoute
    }
    '/_authenticated/management/companies/$id': {
      id: '/_authenticated/management/companies/$id'
      path: '/$id'
      fullPath: '/management/companies/$id'
      preLoaderRoute: typeof AuthenticatedManagementCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedManagementCompaniesRoute
    }
    '/_authenticated/app/chat/$threadId': {
      id: '/_authenticated/app/chat/$threadId'
      path: '/$threadId'
      fullPath: '/app/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedAppChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/app/academy/teacher': {
      id: '/_authenticated/app/academy/teacher'
      path: '/academy/teacher'
      fullPath: '/app/academy/teacher'
      preLoaderRoute: typeof AuthenticatedAppAcademyTeacherRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/settings': {
      id: '/_authenticated/app/academy/settings'
      path: '/academy/settings'
      fullPath: '/app/academy/settings'
      preLoaderRoute: typeof AuthenticatedAppAcademySettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/kb': {
      id: '/_authenticated/app/academy/kb'
      path: '/academy/kb'
      fullPath: '/app/academy/kb'
      preLoaderRoute: typeof AuthenticatedAppAcademyKbRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/courses': {
      id: '/_authenticated/app/academy/courses'
      path: '/academy/courses'
      fullPath: '/app/academy/courses'
      preLoaderRoute: typeof AuthenticatedAppAcademyCoursesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/certificates': {
      id: '/_authenticated/app/academy/certificates'
      path: '/academy/certificates'
      fullPath: '/app/academy/certificates'
      preLoaderRoute: typeof AuthenticatedAppAcademyCertificatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/analytics': {
      id: '/_authenticated/app/academy/analytics'
      path: '/academy/analytics'
      fullPath: '/app/academy/analytics'
      preLoaderRoute: typeof AuthenticatedAppAcademyAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/v1/license/releases': {
      id: '/api/public/v1/license/releases'
      path: '/api/public/v1/license/releases'
      fullPath: '/api/public/v1/license/releases'
      preLoaderRoute: typeof ApiPublicV1LicenseReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/license/heartbeat': {
      id: '/api/public/v1/license/heartbeat'
      path: '/api/public/v1/license/heartbeat'
      fullPath: '/api/public/v1/license/heartbeat'
      preLoaderRoute: typeof ApiPublicV1LicenseHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/academy/path/$pathId': {
      id: '/_authenticated/app/academy/path/$pathId'
      path: '/academy/path/$pathId'
      fullPath: '/app/academy/path/$pathId'
      preLoaderRoute: typeof AuthenticatedAppAcademyPathPathIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/academy/lesson/$lessonId': {
      id: '/_authenticated/app/academy/lesson/$lessonId'
      path: '/academy/lesson/$lessonId'
      fullPath: '/app/academy/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedAppAcademyLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatThreadIdRoute: typeof AuthenticatedAppChatThreadIdRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatThreadIdRoute: AuthenticatedAppChatThreadIdRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppFaqRoute: typeof AuthenticatedAppFaqRoute
  AuthenticatedAppKnowledgeRoute: typeof AuthenticatedAppKnowledgeRoute
  AuthenticatedAppModulesRoute: typeof AuthenticatedAppModulesRoute
  AuthenticatedAppOrganizationRoute: typeof AuthenticatedAppOrganizationRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppUpdatesRoute: typeof AuthenticatedAppUpdatesRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAcademyAnalyticsRoute: typeof AuthenticatedAppAcademyAnalyticsRoute
  AuthenticatedAppAcademyCertificatesRoute: typeof AuthenticatedAppAcademyCertificatesRoute
  AuthenticatedAppAcademyCoursesRoute: typeof AuthenticatedAppAcademyCoursesRoute
  AuthenticatedAppAcademyKbRoute: typeof AuthenticatedAppAcademyKbRoute
  AuthenticatedAppAcademySettingsRoute: typeof AuthenticatedAppAcademySettingsRoute
  AuthenticatedAppAcademyTeacherRoute: typeof AuthenticatedAppAcademyTeacherRoute
  AuthenticatedAppAcademyIndexRoute: typeof AuthenticatedAppAcademyIndexRoute
  AuthenticatedAppAcademyLessonLessonIdRoute: typeof AuthenticatedAppAcademyLessonLessonIdRoute
  AuthenticatedAppAcademyPathPathIdRoute: typeof AuthenticatedAppAcademyPathPathIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppFaqRoute: AuthenticatedAppFaqRoute,
  AuthenticatedAppKnowledgeRoute: AuthenticatedAppKnowledgeRoute,
  AuthenticatedAppModulesRoute: AuthenticatedAppModulesRoute,
  AuthenticatedAppOrganizationRoute: AuthenticatedAppOrganizationRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppUpdatesRoute: AuthenticatedAppUpdatesRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAcademyAnalyticsRoute: AuthenticatedAppAcademyAnalyticsRoute,
  AuthenticatedAppAcademyCertificatesRoute:
    AuthenticatedAppAcademyCertificatesRoute,
  AuthenticatedAppAcademyCoursesRoute: AuthenticatedAppAcademyCoursesRoute,
  AuthenticatedAppAcademyKbRoute: AuthenticatedAppAcademyKbRoute,
  AuthenticatedAppAcademySettingsRoute: AuthenticatedAppAcademySettingsRoute,
  AuthenticatedAppAcademyTeacherRoute: AuthenticatedAppAcademyTeacherRoute,
  AuthenticatedAppAcademyIndexRoute: AuthenticatedAppAcademyIndexRoute,
  AuthenticatedAppAcademyLessonLessonIdRoute:
    AuthenticatedAppAcademyLessonLessonIdRoute,
  AuthenticatedAppAcademyPathPathIdRoute:
    AuthenticatedAppAcademyPathPathIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedManagementCompaniesRouteChildren {
  AuthenticatedManagementCompaniesIdRoute: typeof AuthenticatedManagementCompaniesIdRoute
}

const AuthenticatedManagementCompaniesRouteChildren: AuthenticatedManagementCompaniesRouteChildren =
  {
    AuthenticatedManagementCompaniesIdRoute:
      AuthenticatedManagementCompaniesIdRoute,
  }

const AuthenticatedManagementCompaniesRouteWithChildren =
  AuthenticatedManagementCompaniesRoute._addFileChildren(
    AuthenticatedManagementCompaniesRouteChildren,
  )

interface AuthenticatedManagementRouteChildren {
  AuthenticatedManagementAuditLogsRoute: typeof AuthenticatedManagementAuditLogsRoute
  AuthenticatedManagementCompaniesRoute: typeof AuthenticatedManagementCompaniesRouteWithChildren
  AuthenticatedManagementCustomersRoute: typeof AuthenticatedManagementCustomersRoute
  AuthenticatedManagementInstallationsRoute: typeof AuthenticatedManagementInstallationsRoute
  AuthenticatedManagementLicensesRoute: typeof AuthenticatedManagementLicensesRoute
  AuthenticatedManagementOwnershipRoute: typeof AuthenticatedManagementOwnershipRoute
  AuthenticatedManagementPortalRoute: typeof AuthenticatedManagementPortalRoute
  AuthenticatedManagementReleasesRoute: typeof AuthenticatedManagementReleasesRoute
  AuthenticatedManagementSettingsRoute: typeof AuthenticatedManagementSettingsRoute
  AuthenticatedManagementSupportRoute: typeof AuthenticatedManagementSupportRoute
  AuthenticatedManagementIndexRoute: typeof AuthenticatedManagementIndexRoute
}

const AuthenticatedManagementRouteChildren: AuthenticatedManagementRouteChildren =
  {
    AuthenticatedManagementAuditLogsRoute:
      AuthenticatedManagementAuditLogsRoute,
    AuthenticatedManagementCompaniesRoute:
      AuthenticatedManagementCompaniesRouteWithChildren,
    AuthenticatedManagementCustomersRoute:
      AuthenticatedManagementCustomersRoute,
    AuthenticatedManagementInstallationsRoute:
      AuthenticatedManagementInstallationsRoute,
    AuthenticatedManagementLicensesRoute: AuthenticatedManagementLicensesRoute,
    AuthenticatedManagementOwnershipRoute:
      AuthenticatedManagementOwnershipRoute,
    AuthenticatedManagementPortalRoute: AuthenticatedManagementPortalRoute,
    AuthenticatedManagementReleasesRoute: AuthenticatedManagementReleasesRoute,
    AuthenticatedManagementSettingsRoute: AuthenticatedManagementSettingsRoute,
    AuthenticatedManagementSupportRoute: AuthenticatedManagementSupportRoute,
    AuthenticatedManagementIndexRoute: AuthenticatedManagementIndexRoute,
  }

const AuthenticatedManagementRouteWithChildren =
  AuthenticatedManagementRoute._addFileChildren(
    AuthenticatedManagementRouteChildren,
  )

interface AuthenticatedPortalAdminRouteChildren {
  AuthenticatedPortalAdminDownloadsRoute: typeof AuthenticatedPortalAdminDownloadsRoute
  AuthenticatedPortalAdminIndexRoute: typeof AuthenticatedPortalAdminIndexRoute
}

const AuthenticatedPortalAdminRouteChildren: AuthenticatedPortalAdminRouteChildren =
  {
    AuthenticatedPortalAdminDownloadsRoute:
      AuthenticatedPortalAdminDownloadsRoute,
    AuthenticatedPortalAdminIndexRoute: AuthenticatedPortalAdminIndexRoute,
  }

const AuthenticatedPortalAdminRouteWithChildren =
  AuthenticatedPortalAdminRoute._addFileChildren(
    AuthenticatedPortalAdminRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAdminRoute: typeof AuthenticatedPortalAdminRouteWithChildren
  AuthenticatedPortalDocumentationRoute: typeof AuthenticatedPortalDocumentationRoute
  AuthenticatedPortalDownloadsRoute: typeof AuthenticatedPortalDownloadsRoute
  AuthenticatedPortalReleaseNotesRoute: typeof AuthenticatedPortalReleaseNotesRoute
  AuthenticatedPortalSubscriptionRoute: typeof AuthenticatedPortalSubscriptionRoute
  AuthenticatedPortalSupportRoute: typeof AuthenticatedPortalSupportRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAdminRoute: AuthenticatedPortalAdminRouteWithChildren,
  AuthenticatedPortalDocumentationRoute: AuthenticatedPortalDocumentationRoute,
  AuthenticatedPortalDownloadsRoute: AuthenticatedPortalDownloadsRoute,
  AuthenticatedPortalReleaseNotesRoute: AuthenticatedPortalReleaseNotesRoute,
  AuthenticatedPortalSubscriptionRoute: AuthenticatedPortalSubscriptionRoute,
  AuthenticatedPortalSupportRoute: AuthenticatedPortalSupportRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedManagementRoute: typeof AuthenticatedManagementRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedManagementRoute: AuthenticatedManagementRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LegalRouteRouteChildren {
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDpaRoute: typeof LegalDpaRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalResponsibleAiRoute: typeof LegalResponsibleAiRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDpaRoute: LegalDpaRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalResponsibleAiRoute: LegalResponsibleAiRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  DocumentationRoute: DocumentationRoute,
  FirstRunRoute: FirstRunRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  McpRoute: McpRoute,
  ModulesRoute: ModulesRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SelfHostedRoute: SelfHostedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SsoSigninRoute: SsoSigninRoute,
  SupportRoute: SupportRoute,
  WindowsOnlyRoute: WindowsOnlyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAcademyChatRoute: ApiAcademyChatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCustomerWriterRoute: ApiCustomerWriterRoute,
  ApiInternalChatRoute: ApiInternalChatRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiWorkspaceChatRoute: ApiWorkspaceChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicV1FaqsRoute: ApiPublicV1FaqsRoute,
  ApiPublicV1KnowledgeRoute: ApiPublicV1KnowledgeRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicV1LicenseHeartbeatRoute: ApiPublicV1LicenseHeartbeatRoute,
  ApiPublicV1LicenseReleasesRoute: ApiPublicV1LicenseReleasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
