// OPSQAI Transport — country packs (client-safe).
//
// A country pack is configuration, not law: it seeds the document types a
// fleet in that country actually keeps, the local name of the periodic
// roadworthiness test, and the CMR consignment-note wording. Nothing here is
// automatically enforced — the workspace only tracks what the company records.

export type CountryCode = "ro" | "de" | "at" | "generic";

export interface DocTypeDef {
  key: string;
  label: { en: string; de: string; ro: string };
  owner: "vehicle" | "driver" | "carrier";
  /** Typical renewal cadence in months, used only to pre-fill a date. */
  months?: number;
}

const COMMON_VEHICLE: DocTypeDef[] = [
  {
    key: "insurance",
    owner: "vehicle",
    months: 12,
    label: { en: "Motor liability insurance", de: "Kfz-Haftpflicht", ro: "RCA" },
  },
  {
    key: "cmr_insurance",
    owner: "vehicle",
    months: 12,
    label: { en: "CMR / cargo insurance", de: "CMR-Versicherung", ro: "Asigurare CMR" },
  },
  {
    key: "tacho_calibration",
    owner: "vehicle",
    months: 24,
    label: { en: "Tachograph calibration", de: "Tachograph-Kalibrierung", ro: "Verificare tahograf" },
  },
];

const COMMON_DRIVER: DocTypeDef[] = [
  {
    key: "driving_licence",
    owner: "driver",
    label: { en: "Driving licence", de: "Führerschein", ro: "Permis de conducere" },
  },
  {
    key: "driver_card",
    owner: "driver",
    months: 60,
    label: { en: "Driver card", de: "Fahrerkarte", ro: "Cartelă tahograf" },
  },
  {
    key: "medical",
    owner: "driver",
    months: 12,
    label: { en: "Medical fitness", de: "Ärztliche Untersuchung", ro: "Aviz medical" },
  },
  {
    key: "cpc",
    owner: "driver",
    months: 60,
    label: { en: "Professional competence", de: "Berufskraftfahrer-Qualifikation", ro: "Atestat profesional" },
  },
];

const COMMON_CARRIER: DocTypeDef[] = [
  {
    key: "operator_licence",
    owner: "carrier",
    label: { en: "Operator licence", de: "Gemeinschaftslizenz", ro: "Licență de transport" },
  },
  {
    key: "liability",
    owner: "carrier",
    months: 12,
    label: { en: "Carrier liability", de: "Verkehrshaftung", ro: "Asigurare de răspundere" },
  },
];

export interface CountryPack {
  code: CountryCode;
  label: string;
  /** Local name of the periodic technical inspection. */
  inspection: { key: string; label: { en: string; de: string; ro: string }; months: number };
  docTypes: DocTypeDef[];
  cmr: {
    /** Heading printed on the consignment note. */
    title: string;
    subtitle: string;
    /** Legal reference line printed in the footer. */
    footer: string;
  };
  distanceUnit: "km" | "mi";
  weightUnit: "kg" | "lb";
}

function pack(
  code: CountryCode,
  label: string,
  inspection: CountryPack["inspection"],
  cmr: CountryPack["cmr"],
): CountryPack {
  return {
    code,
    label,
    inspection,
    docTypes: [
      { ...inspection, owner: "vehicle" },
      ...COMMON_VEHICLE,
      ...COMMON_DRIVER,
      ...COMMON_CARRIER,
    ],
    cmr,
    distanceUnit: "km",
    weightUnit: "kg",
  };
}

export const COUNTRY_PACKS: Record<CountryCode, CountryPack> = {
  ro: pack(
    "ro",
    "România",
    {
      key: "itp",
      months: 12,
      label: { en: "Periodic technical inspection (ITP)", de: "Technische Prüfung (ITP)", ro: "ITP" },
    },
    {
      title: "SCRISOARE DE TRANSPORT — CMR",
      subtitle: "Transport internațional rutier de mărfuri",
      footer: "Convenția CMR (Geneva, 19.05.1956) — exemplar editabil generat de OPSQAI.",
    },
  ),
  de: pack(
    "de",
    "Deutschland",
    {
      key: "tuv",
      months: 24,
      label: { en: "Roadworthiness test (TÜV)", de: "Hauptuntersuchung (TÜV)", ro: "Inspecție tehnică (TÜV)" },
    },
    {
      title: "FRACHTBRIEF — CMR",
      subtitle: "Internationaler Straßengüterverkehr",
      footer: "CMR-Übereinkommen (Genf, 19.05.1956) — bearbeitbare Ausgabe von OPSQAI.",
    },
  ),
  at: pack(
    "at",
    "Österreich",
    {
      key: "pickerl",
      months: 12,
      label: { en: "Roadworthiness test (§57a)", de: "Begutachtung (§57a Pickerl)", ro: "Inspecție tehnică (§57a)" },
    },
    {
      title: "FRACHTBRIEF — CMR",
      subtitle: "Internationaler Straßengüterverkehr",
      footer: "CMR-Übereinkommen (Genf, 19.05.1956) — bearbeitbare Ausgabe von OPSQAI.",
    },
  ),
  generic: pack(
    "generic",
    "International / other",
    {
      key: "inspection",
      months: 12,
      label: {
        en: "Periodic technical inspection",
        de: "Technische Prüfung",
        ro: "Inspecție tehnică periodică",
      },
    },
    {
      title: "CONSIGNMENT NOTE — CMR",
      subtitle: "International carriage of goods by road",
      footer: "CMR Convention (Geneva, 19.05.1956) — editable issue generated by OPSQAI.",
    },
  ),
};

export function countryPack(code: string | null | undefined): CountryPack {
  const key = (code ?? "generic").toLowerCase() as CountryCode;
  return COUNTRY_PACKS[key] ?? COUNTRY_PACKS.generic;
}

export function docTypeLabel(
  code: string | null | undefined,
  docType: string,
  lang: "en" | "de" | "ro",
): string {
  const found = countryPack(code).docTypes.find((d) => d.key === docType);
  return found ? found.label[lang] : docType;
}

export const COUNTRY_OPTIONS = (Object.keys(COUNTRY_PACKS) as CountryCode[]).map((code) => ({
  code,
  label: COUNTRY_PACKS[code].label,
}));
