import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";
import type { IDirectMessageRepository, DirectMessageRecord } from "@/lib/providers/interfaces";

export function createSupabaseDirectMessageRepository(client:SupabaseClient<Database>):IDirectMessageRepository{
  const map=(r:any):DirectMessageRecord=>({id:r.id,conversationId:r.conversation_id,senderId:r.sender_id,body:r.body,attachments:Array.isArray(r.attachments)?r.attachments:[],createdAt:r.created_at,editedAt:r.edited_at,deletedAt:r.deleted_at});
  return{
    async searchContacts(_userId,query,limit){const{data,error}=await client.rpc("search_chat_contacts",{_q:query,_limit:limit});if(error)throw new Error(error.message);return(data??[]).map((r:any)=>({id:r.id,fullName:r.full_name,email:r.email,avatarUrl:r.avatar_url,isStaff:r.is_staff,isColleague:r.is_colleague}));},
    async listConversations(userId){const{data:members,error}=await client.from("direct_conversation_members").select("conversation_id,last_read_at").eq("user_id",userId);if(error)throw new Error(error.message);const ids=(members??[]).map((m)=>m.conversation_id);if(!ids.length)return[];const[{data:convs},{data:all},{data:msgs}]=await Promise.all([client.from("direct_conversations").select("id,created_at,last_message_at").in("id",ids).order("last_message_at",{ascending:false}),client.from("direct_conversation_members").select("conversation_id,user_id").in("conversation_id",ids),client.from("direct_messages").select("conversation_id,sender_id,body,attachments,created_at").in("conversation_id",ids).order("created_at",{ascending:false})]);const peerIds=(all??[]).filter((m)=>m.user_id!==userId).map((m)=>m.user_id);const{data:profiles}=peerIds.length?await client.from("profiles").select("id,full_name,avatar_url").in("id",peerIds):{data:[]};return(convs??[]).map((c)=>{const peerId=(all??[]).find((m)=>m.conversation_id===c.id&&m.user_id!==userId)?.user_id;const p=(profiles??[]).find((x)=>x.id===peerId);const last=(msgs??[]).find((m)=>m.conversation_id===c.id);const read=(members??[]).find((m)=>m.conversation_id===c.id)?.last_read_at??"1970-01-01";return{id:c.id,createdAt:c.created_at,lastMessageAt:c.last_message_at,peer:peerId?{id:peerId,fullName:p?.full_name??"",email:"",avatarUrl:p?.avatar_url??null,isStaff:false,isColleague:true}:null,lastMessage:last?{body:last.body,createdAt:last.created_at,senderId:last.sender_id,hasAttachments:Array.isArray(last.attachments)&&last.attachments.length>0}:null,unreadCount:(msgs??[]).filter((m)=>m.conversation_id===c.id&&m.sender_id!==userId&&m.created_at>read).length};});},
    async findOrCreate(_userId,targetUserId){const{data,error}=await client.rpc("find_or_create_direct_conversation",{_target:targetUserId});if(error)throw new Error(error.message);return data as string;},
    async listMessages(_userId,conversationId,before,limit){let q=client.from("direct_messages").select("*").eq("conversation_id",conversationId).order("created_at",{ascending:false}).limit(limit);if(before)q=q.lt("created_at",before);const{data,error}=await q;if(error)throw new Error(error.message);return(data??[]).reverse().map(map);},
    async send(userId,input){const{data,error}=await client.from("direct_messages").insert({conversation_id:input.conversationId,sender_id:userId,body:input.body,attachments:input.attachments} as never).select("*").single();if(error)throw new Error(error.message);return map(data);},
    async markRead(userId,conversationId){const{error}=await client.from("direct_conversation_members").update({last_read_at:new Date().toISOString()}).eq("user_id",userId).eq("conversation_id",conversationId);if(error)throw new Error(error.message);},
  };
}